from __future__ import annotations

import json
import os
import shutil
import subprocess
from pathlib import Path

import pytest

import splashdown as sd
from conftest import (
    _git_init,
    _make_ios,
)


def _native_hook(cwd: Path) -> Path:
    raw = Path(
        subprocess.check_output(
            ["git", "rev-parse", "--git-path", "hooks/post-checkout"],
            cwd=cwd,
            text=True,
        ).strip()
    )
    return raw if raw.is_absolute() else cwd / raw


def test_detect_hook_manager_clean(tmp_path):
    assert sd._detect_hook_manager(tmp_path) == "none"


def test_detect_hook_manager_tolerates_permission_denied_git(tmp_path, monkeypatch):
    monkeypatch.setattr(
        sd.hooks.subprocess,
        "check_output",
        lambda *args, **kwargs: (_ for _ in ()).throw(PermissionError("denied")),
    )

    assert sd._detect_hook_manager(tmp_path) == "none"


def test_detect_hook_manager_lefthook_yml(tmp_path):
    (tmp_path / "lefthook.yml").write_text("pre-commit:\n  commands: {}\n")
    assert sd._detect_hook_manager(tmp_path) == "lefthook"


def test_detect_hook_manager_lefthook_yaml(tmp_path):
    (tmp_path / "lefthook.yaml").write_text("")
    assert sd._detect_hook_manager(tmp_path) == "lefthook"


def test_detect_hook_manager_lefthook_dotted(tmp_path):
    (tmp_path / ".lefthook.yml").write_text("")
    assert sd._detect_hook_manager(tmp_path) == "lefthook"


def test_detect_hook_manager_lefthook_via_pkg(tmp_path):
    (tmp_path / "package.json").write_text('{"devDependencies": {"lefthook": "^1.0"}}')
    assert sd._detect_hook_manager(tmp_path) == "lefthook"


def test_detect_hook_manager_ignores_nonobject_package_json(tmp_path):
    (tmp_path / "package.json").write_text('["lefthook"]')

    assert sd._detect_hook_manager(tmp_path) == "none"


def test_detect_hook_manager_husky(tmp_path):
    (tmp_path / ".husky").mkdir()
    assert sd._detect_hook_manager(tmp_path) == "husky"


def test_detect_hook_manager_pre_commit(tmp_path):
    (tmp_path / ".pre-commit-config.yaml").write_text("repos: []\n")
    assert sd._detect_hook_manager(tmp_path) == "pre-commit"


def test_detect_hook_manager_prek(tmp_path):
    (tmp_path / "prek.toml").write_text("")
    assert sd._detect_hook_manager(tmp_path) == "prek"


def test_detect_hook_manager_simple_git_hooks_json(tmp_path):
    (tmp_path / ".simple-git-hooks.json").write_text("{}")
    assert sd._detect_hook_manager(tmp_path) == "simple-git-hooks"


def test_detect_hook_manager_simple_git_hooks_package_key(tmp_path):
    (tmp_path / "package.json").write_text('{"simple-git-hooks": {"pre-commit": "npm test"}}')
    assert sd._detect_hook_manager(tmp_path) == "simple-git-hooks"


def test_detect_hook_manager_overcommit(tmp_path):
    (tmp_path / ".overcommit.yml").write_text("PostCheckout:\n  ALL:\n    enabled: true\n")
    assert sd._detect_hook_manager(tmp_path) == "overcommit"


def test_detect_prefers_a_configuration_file_over_a_package_dependency(tmp_path):
    (tmp_path / ".husky").mkdir()
    (tmp_path / "package.json").write_text('{"devDependencies": {"lefthook": "^1.0"}}')

    detection = sd.detect_hook_configuration(tmp_path)

    assert detection.manager == "husky"
    assert detection.reason == "its configuration file is in the checkout"


def test_detect_reports_two_configured_managers_as_a_conflict(tmp_path):
    (tmp_path / "lefthook.yml").write_text("")
    (tmp_path / ".pre-commit-config.yaml").write_text("repos: []\n")

    detection = sd.detect_hook_configuration(tmp_path)

    assert detection.manager == "conflict"
    assert detection.candidates == ("lefthook", "pre-commit")


def test_detect_prefers_the_installed_post_checkout_hook_over_configuration(tmp_path):
    _git_init(tmp_path)
    (tmp_path / "lefthook.yml").write_text("")
    (tmp_path / ".pre-commit-config.yaml").write_text("repos: []\n")
    hook = _native_hook(tmp_path)
    hook.parent.mkdir(parents=True, exist_ok=True)
    hook.write_text("#!/bin/sh\n# File generated by pre-commit: https://pre-commit.com\n")

    detection = sd.detect_hook_configuration(tmp_path)

    assert detection.manager == "pre-commit"
    assert detection.reason == "the installed post-checkout hook was generated by it"


def test_detect_prefers_another_installed_hook_over_configuration(tmp_path):
    _git_init(tmp_path)
    (tmp_path / "lefthook.yml").write_text("")
    (tmp_path / ".pre-commit-config.yaml").write_text("repos: []\n")
    hooks = _native_hook(tmp_path).parent
    hooks.mkdir(parents=True, exist_ok=True)
    (hooks / "pre-commit").write_text("#!/bin/sh\n# File generated by prek: github.com/j178/prek\n")

    detection = sd.detect_hook_configuration(tmp_path)

    assert detection.manager == "prek"
    assert detection.reason == "an installed Git hook was generated by it"


def test_detect_ignores_splashdowns_own_native_hook(tmp_path):
    _git_init(tmp_path)
    sd._wire_post_checkout_native(tmp_path)

    assert sd._detect_hook_manager(tmp_path) == "none"


def test_detect_ignores_sample_hooks(tmp_path):
    _git_init(tmp_path)
    hooks = _native_hook(tmp_path).parent
    hooks.mkdir(parents=True, exist_ok=True)
    (hooks / "pre-commit.sample").write_text("# File generated by pre-commit\n")

    assert sd._detect_hook_manager(tmp_path) == "none"


def test_detect_husky_from_core_hooks_path(tmp_path):
    _git_init(tmp_path)
    subprocess.run(["git", "config", "core.hooksPath", ".husky/_"], cwd=tmp_path, check=True)

    detection = sd.detect_hook_configuration(tmp_path)

    assert detection.manager == "husky"
    assert "core.hooksPath" in detection.reason


def test_detect_custom_core_hooks_path_outranks_a_recognized_config(tmp_path):
    _git_init(tmp_path)
    (tmp_path / "lefthook.yml").write_text("")
    subprocess.run(["git", "config", "core.hooksPath", ".githooks"], cwd=tmp_path, check=True)

    assert sd._detect_hook_manager(tmp_path) == "core-hookspath-other"


def test_wire_lefthook_appends_block_when_absent(tmp_path):
    (tmp_path / "lefthook.yml").write_text(
        "pre-commit:\n  commands:\n    lint:\n      run: echo lint\n"
    )
    sd._wire_post_checkout_lefthook(tmp_path)
    text = (tmp_path / "lefthook.yml").read_text()
    assert "pre-commit:" in text
    assert "post-checkout:" in text
    assert "splashdown:" in text
    assert '"$SPLASH" hook post-checkout' in text


def test_wire_lefthook_inserts_under_existing_post_checkout(tmp_path):
    (tmp_path / "lefthook.yml").write_text(
        "post-checkout:\n  commands:\n    notify:\n      run: echo hi\n"
    )
    sd._wire_post_checkout_lefthook(tmp_path)
    text = (tmp_path / "lefthook.yml").read_text()
    assert "notify:" in text
    assert "splashdown:" in text
    assert sum(line == "post-checkout:" for line in text.splitlines()) == 1


def test_wire_lefthook_idempotent(tmp_path):
    (tmp_path / "lefthook.yml").write_text("")
    sd._wire_post_checkout_lefthook(tmp_path)
    once = (tmp_path / "lefthook.yml").read_text()
    sd._wire_post_checkout_lefthook(tmp_path)
    twice = (tmp_path / "lefthook.yml").read_text()
    assert once == twice
    assert twice.count("splashdown:") == 1


def test_wire_lefthook_creates_config_if_only_pkg_dep(tmp_path):
    (tmp_path / "package.json").write_text('{"devDependencies": {"lefthook": "^1.0"}}')
    sd._wire_post_checkout_lefthook(tmp_path)
    assert (tmp_path / "lefthook.yml").exists()
    assert "splashdown:" in (tmp_path / "lefthook.yml").read_text()


def test_wire_lefthook_refuses_symlinked_config(tmp_path):
    outside = tmp_path.parent / f"{tmp_path.name}-lefthook.yml"
    original = "pre-commit:\n  commands: {}\n"
    outside.write_text(original)
    (tmp_path / "lefthook.yml").symlink_to(outside)

    with pytest.raises(ValueError, match="symlink"):
        sd._wire_post_checkout_lefthook(tmp_path)

    assert outside.read_text() == original


def test_wire_husky_creates_executable_hook(tmp_path):
    sd._wire_post_checkout_husky(tmp_path)
    hook = tmp_path / ".husky" / "post-checkout"
    assert hook.exists()
    assert os.access(hook, os.X_OK)
    assert "splash" in hook.read_text()


def test_wire_husky_refuses_symlinked_hook(tmp_path):
    husky = tmp_path / ".husky"
    husky.mkdir()
    outside = tmp_path.parent / f"{tmp_path.name}-husky-post-checkout"
    original = sd.hooks.LEGACY_POST_CHECKOUT_HOOK
    outside.write_text(original)
    (husky / "post-checkout").symlink_to(outside)

    with pytest.raises(ValueError, match="symlink"):
        sd._wire_post_checkout_husky(tmp_path)

    assert outside.read_text() == original


def test_wire_native_refuses_symlinked_hook(tmp_path):
    _git_init(tmp_path)
    hook = _native_hook(tmp_path)
    hook.parent.mkdir(parents=True, exist_ok=True)
    outside = tmp_path.parent / f"{tmp_path.name}-native-post-checkout"
    original = sd.hooks.LEGACY_POST_CHECKOUT_HOOK
    outside.write_text(original)
    hook.symlink_to(outside)

    with pytest.raises(ValueError, match="symlink"):
        sd._wire_post_checkout_native(tmp_path)

    assert outside.read_text() == original


def test_ensure_hook_chooses_lefthook(tmp_path):
    (tmp_path / "lefthook.yml").write_text("")
    sd._ensure_post_checkout_hook(tmp_path)
    assert "splashdown:" in (tmp_path / "lefthook.yml").read_text()


def test_ensure_hook_chooses_husky(tmp_path):
    (tmp_path / ".husky").mkdir()
    sd._ensure_post_checkout_hook(tmp_path)
    assert (tmp_path / ".husky" / "post-checkout").exists()


def test_ensure_hook_clean_writes_native_git_hook(tmp_path):
    _git_init(tmp_path)
    sd._ensure_post_checkout_hook(tmp_path)
    hook = _native_hook(tmp_path)
    assert hook.read_text() == sd.hooks.POST_CHECKOUT_HOOK
    assert os.access(hook, os.X_OK)


def test_wire_native_hook_preserves_user_owned_hook(tmp_path, capsys):
    _git_init(tmp_path)
    hook = _native_hook(tmp_path)
    hook.write_text("#!/bin/sh\necho user-hook\n")

    sd._wire_post_checkout_native(tmp_path)

    assert hook.read_text() == "#!/bin/sh\necho user-hook\n"
    assert "leaving it untouched" in capsys.readouterr().err


def test_configure_hook_writes_lefthook_config(tmp_path):
    (tmp_path / "lefthook.yml").write_text("")
    sd._configure_post_checkout_hook(tmp_path)
    assert "splashdown:" in (tmp_path / "lefthook.yml").read_text()


def test_configure_hook_writes_husky_script(tmp_path):
    (tmp_path / ".husky").mkdir()
    sd._configure_post_checkout_hook(tmp_path)
    assert (tmp_path / ".husky" / "post-checkout").exists()


def test_configure_hook_leaves_native_hook_to_activation(tmp_path, capsys):
    _git_init(tmp_path)
    sd._configure_post_checkout_hook(tmp_path)
    assert not _native_hook(tmp_path).exists()
    assert "installed by `splash trust`" in capsys.readouterr().err


def test_configure_hook_reports_a_directory_outside_git(tmp_path, capsys):
    sd._configure_post_checkout_hook(tmp_path)
    assert "not a Git checkout; post-checkout hook not installed" in capsys.readouterr().err


def _record_manager_installs(monkeypatch) -> list[tuple[Path, str]]:
    installs: list[tuple[Path, str]] = []
    monkeypatch.setattr(
        sd.hooks,
        "_run_manager_install",
        lambda cwd, argv, label: bool(installs.append((cwd, label))) or True,
    )
    return installs


def test_configure_hook_does_not_install_lefthook(tmp_path, monkeypatch):
    installs = _record_manager_installs(monkeypatch)
    (tmp_path / "lefthook.yml").write_text("")

    sd._configure_post_checkout_hook(tmp_path)

    assert installs == []


def test_ensure_hook_installs_lefthook_after_wiring(tmp_path, monkeypatch):
    installs = _record_manager_installs(monkeypatch)
    (tmp_path / "lefthook.yml").write_text("")

    sd._ensure_post_checkout_hook(tmp_path)

    assert installs == [(tmp_path, "lefthook install")]


def test_ensure_hook_skips_install_for_a_modified_splashdown_job(tmp_path, monkeypatch):
    installs = _record_manager_installs(monkeypatch)
    (tmp_path / "lefthook.yml").write_text(
        "post-checkout:\n  commands:\n    splashdown:\n      run: custom\n"
    )

    sd._ensure_post_checkout_hook(tmp_path)

    assert installs == []


def test_cmd_init_writes_lefthook_config_without_installing_hooks(tmp_path, monkeypatch):
    installs = _record_manager_installs(monkeypatch)
    _git_init(tmp_path)
    (tmp_path / "lefthook.yml").write_text("")

    sd.cmd_init(tmp_path)

    assert "splashdown:" in (tmp_path / "lefthook.yml").read_text()
    assert installs == []


def test_cmd_init_writes_husky_hook_script(tmp_path):
    _git_init(tmp_path)
    (tmp_path / ".husky").mkdir()

    sd.cmd_init(tmp_path)

    assert "splash" in (tmp_path / ".husky" / "post-checkout").read_text()


def test_cmd_trust_installs_lefthook_hooks(tmp_path, monkeypatch):
    _git_init(tmp_path)
    (tmp_path / "lefthook.yml").write_text("")
    sd.cmd_init(tmp_path)
    installs = _record_manager_installs(monkeypatch)

    assert sd.main(["--cwd", str(tmp_path), "trust"]) == 0

    assert installs == [(tmp_path.resolve(), "lefthook install")]


def test_lefthook_install_does_not_invoke_project_package_managers(tmp_path, monkeypatch):
    (tmp_path / "package.json").write_text('{"devDependencies":{"lefthook":"1"}}')
    (tmp_path / "yarn.lock").write_text("")
    calls: list[list[str]] = []

    def run(argv, **_kwargs):
        calls.append(list(argv))
        return subprocess.CompletedProcess(argv, 0)

    monkeypatch.setattr(sd.hooks.subprocess, "run", run)

    sd.hooks._run_lefthook_install(tmp_path)

    assert calls == [["lefthook", "install"]]


def test_doctor_help_in_cli(capsys):
    with pytest.raises(SystemExit):
        sd.main(["doctor", "--help"])
    out = capsys.readouterr().out
    assert "--fix" in out
    assert "--framework" in out


def test_doctor_no_framework_returns_1(tmp_path, capsys):
    rc = sd.cmd_doctor(tmp_path)
    assert rc == 1
    err = capsys.readouterr().err
    assert "framework" in err.lower()


def test_doctor_unknown_framework_returns_usage_error(tmp_path, capsys):
    rc = sd.cmd_doctor(tmp_path, framework_override="nonesuch")
    assert rc == 2
    err = capsys.readouterr().err
    assert "unknown framework" in err.lower()


def test_doctor_cli_rejects_unknown_framework(capsys):
    with pytest.raises(SystemExit) as exc:
        sd.main(["doctor", "--framework", "nonesuch"])
    assert exc.value.code == 2
    assert "nonesuch" in capsys.readouterr().err


def test_doctor_known_checkless_framework_reports_healthy(tmp_path, capsys):
    # nextjs reads PORT straight from the environment — "checked, nothing to
    # wire", not a shrug.
    assert sd.PROFILES["nextjs"].env_only  # premise: still checkless and env-only
    rc = sd.cmd_doctor(tmp_path, framework_override="nextjs")
    assert rc == 0
    err = capsys.readouterr().err
    assert "no wiring checks needed for" in err
    assert "no wiring checks defined" not in err


def test_doctor_checkless_but_not_env_only_keeps_the_shrug(tmp_path, capsys):
    # Skipping Expo's optional Watchman check must not imply its Metro config was verified.
    assert not sd.PROFILES["expo"].env_only
    rc = sd.cmd_doctor(tmp_path, framework_override="expo")
    assert rc == 0
    err = capsys.readouterr().err
    assert "watchman-root: not applicable" in err
    assert "no wiring checks needed for" not in err


def test_doctor_checks_app_subdirectory_from_recipe(tmp_path, capsys):
    # The app lives in a subdir, so root detection misses it. Doctor must check
    # the declared app path, not silently pass having inspected nothing.
    app = tmp_path / "apps" / "web"
    app.mkdir(parents=True)
    (app / "vite.config.ts").write_text("""\
import { defineConfig, loadEnv } from "vite";
export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, import.meta.dirname, "");
  return { server: { port: Number(env.WEB_DEV_PORT ?? 5173) } };
});
""")
    (tmp_path / "splashdown.toml").write_text(
        '[apps.web]\npath = "apps/web"\nprofile = "vite"\nresources = []\n'
    )
    assert sd.cmd_doctor(tmp_path) == 1
    err = capsys.readouterr().err
    assert "not applicable" not in err
    assert sd.cmd_doctor(tmp_path, fix=True) == 0
    assert "process.env.WEB_DEV_PORT" in (app / "vite.config.ts").read_text()


def test_doctor_ambiguous_multi_app_reports_candidates(tmp_path, capsys):
    (tmp_path / "splashdown.toml").write_text(
        '[apps.api]\npath = "apps/api"\nprofile = "node-backend"\nresources = []\n'
        '[apps.web]\npath = "apps/web"\nprofile = "vite"\nresources = []\n'
    )
    assert sd.cmd_doctor(tmp_path) == 1
    err = capsys.readouterr().err
    assert "ambiguous" in err
    assert "api" in err and "web" in err


def test_doctor_rejects_unknown_framework_from_recipe(tmp_path):
    (tmp_path / "splashdown.toml").write_text('[project]\nframework = "nonesuch"\n')
    with pytest.raises(ValueError, match=r"\[project\.framework\]"):
        sd.cmd_doctor(tmp_path)


def test_doctor_uses_filesystem_when_no_recipe(tmp_path):
    (tmp_path / "package.json").write_text('{"dependencies":{"react-native":"0.83"}}')
    assert sd.cmd_doctor(tmp_path) == 1


def test_hook_wiring_check_names_the_lefthook_config_its_autofix_writes(tmp_path):
    (tmp_path / "lefthook.yml").write_text("post-checkout:\n  commands:\n")

    assert sd.wiring._HOOK_WIRING_CHECK.files(tmp_path) == (tmp_path / "lefthook.yml",)


def test_hook_wiring_check_names_the_husky_hook_its_autofix_writes(tmp_path):
    (tmp_path / ".husky").mkdir()

    assert sd.wiring._HOOK_WIRING_CHECK.files(tmp_path) == (tmp_path / ".husky" / "post-checkout",)


def test_hook_wiring_check_names_the_native_hook_its_autofix_writes(tmp_path):
    _git_init(tmp_path)

    files = sd.wiring._HOOK_WIRING_CHECK.files(tmp_path)

    assert len(files) == 1
    assert files[0].name == "post-checkout"
    assert files[0].parent.name == "hooks"


def test_rn_hook_clean_detect_problem(tmp_path):
    status, _ = sd._rn_hook_detect(tmp_path)
    assert status == "problem"


def test_rn_hook_detect_tolerates_permission_denied_git(tmp_path, monkeypatch):
    monkeypatch.setattr(sd.hooks, "_detect_hook_manager", lambda cwd: "none")
    monkeypatch.setattr(
        sd.hooks.subprocess,
        "check_output",
        lambda *args, **kwargs: (_ for _ in ()).throw(PermissionError("denied")),
    )

    status, detail = sd._rn_hook_detect(tmp_path)

    assert status == "problem"
    assert "native post-checkout" in detail


def test_rn_hook_clean_autofix_then_ok(tmp_path):
    _git_init(tmp_path)
    sd._ensure_post_checkout_hook(tmp_path)
    status, _ = sd._rn_hook_detect(tmp_path)
    assert status == "ok"


def test_rn_hook_lefthook_detect_problem(tmp_path):
    (tmp_path / "lefthook.yml").write_text("pre-commit:\n  commands: {}\n")
    status, detail = sd._rn_hook_detect(tmp_path)
    assert status == "problem"
    assert "lefthook" in detail


def test_rn_hook_lefthook_autofix_wires_the_job(tmp_path):
    (tmp_path / "lefthook.yml").write_text(
        "pre-commit:\n  commands:\n    lint:\n      run: echo lint\n"
    )
    sd._ensure_post_checkout_hook(tmp_path)
    assert sd.post_checkout_readiness(tmp_path).ready is True
    text = (tmp_path / "lefthook.yml").read_text()
    assert "lint" in text
    assert "splashdown:" in text


def test_rn_hook_husky_detect_problem(tmp_path):
    (tmp_path / ".husky").mkdir()
    status, _ = sd._rn_hook_detect(tmp_path)
    assert status == "problem"


def test_rn_hook_husky_autofix_warns_until_husky_installs_its_hooks(tmp_path):
    (tmp_path / ".husky").mkdir()
    sd._ensure_post_checkout_hook(tmp_path)
    status, detail = sd._rn_hook_detect(tmp_path)
    assert status == "warning"
    assert "once its hooks are installed" in detail


def test_doctor_fix_wires_hook_in_clean_rn_dir(tmp_path):
    _git_init(tmp_path)
    (tmp_path / "package.json").write_text('{"dependencies":{"react-native":"0.83"}}')
    # Place an empty metro.config.js to satisfy the rn-metro-config "applies" check;
    # detect will still report problem. We're only checking the hook here.
    (tmp_path / "metro.config.js").write_text(
        "module.exports = { server: { port: Number(process.env.RCT_METRO_PORT) || 8081 } };\n"
    )
    assert sd.cmd_doctor(tmp_path) == 1
    assert sd.cmd_doctor(tmp_path, fix=True) == 0
    assert sd.cmd_doctor(tmp_path) == 0
    assert _native_hook(tmp_path).read_text() == sd.hooks.POST_CHECKOUT_HOOK


def test_rn_metro_not_applicable_without_config(tmp_path):
    assert sd._rn_metro_applies(tmp_path) is False


def test_rn_metro_detect_ok_when_env_present(tmp_path):
    (tmp_path / "metro.config.js").write_text(
        "module.exports = { server: { port: Number(process.env.RCT_METRO_PORT) || 8081 } };\n"
    )
    assert sd._rn_metro_detect(tmp_path)[0] == "ok"


def test_rn_metro_detect_problem_for_literal(tmp_path):
    (tmp_path / "metro.config.js").write_text("module.exports = { server: { port: 8083 } };\n")
    status, detail = sd._rn_metro_detect(tmp_path)
    assert status == "problem"
    assert "autofixable" in detail


def test_rn_metro_autofix_replaces_literal(tmp_path):
    (tmp_path / "metro.config.js").write_text(
        "const config = {\n  server: {\n    port: 8083,\n  },\n};\n"
    )
    sd._rn_metro_autofix(tmp_path)
    text = (tmp_path / "metro.config.js").read_text()
    assert "process.env.RCT_METRO_PORT" in text
    assert "|| 8083" in text
    assert sd._rn_metro_detect(tmp_path)[0] == "ok"


@pytest.mark.parametrize(
    ("relative_path", "original", "autofix"),
    [
        (
            Path("metro.config.js"),
            "module.exports = { server: { port: 8083 } };\n",
            sd._rn_metro_autofix,
        ),
        (
            Path("package.json"),
            json.dumps({"scripts": {"start": "react-native start --port 8083"}}),
            sd._rn_pkg_autofix,
        ),
        (
            Path("ios/.xcode.env"),
            "export NODE_BINARY=node\nexport RCT_METRO_PORT=8083\n",
            lambda cwd: sd._rn_xcode_autofix(cwd, "splashdown.env"),
        ),
    ],
)
def test_rn_autofixes_refuse_symlinked_config(tmp_path, relative_path, original, autofix):
    path = tmp_path / relative_path
    path.parent.mkdir(parents=True, exist_ok=True)
    outside = tmp_path.parent / f"{tmp_path.name}-{path.name}"
    outside.write_text(original)
    path.symlink_to(outside)

    with pytest.raises(ValueError, match="symlink"):
        autofix(tmp_path)

    assert outside.read_text() == original


def test_rn_xcode_autofix_refuses_symlinked_parent_directory(tmp_path):
    outside = tmp_path.parent / f"{tmp_path.name}-outside-ios"
    outside.mkdir()
    config = outside / ".xcode.env"
    original = "export NODE_BINARY=node\nexport RCT_METRO_PORT=8083\n"
    config.write_text(original)
    (tmp_path / "ios").symlink_to(outside, target_is_directory=True)

    with pytest.raises(ValueError, match="symlink"):
        sd._rn_xcode_autofix(tmp_path, "splashdown.env")

    assert config.read_text() == original


def test_rn_metro_autofix_idempotent(tmp_path):
    (tmp_path / "metro.config.js").write_text("const config = { server: { port: 8083 } };\n")
    sd._rn_metro_autofix(tmp_path)
    once = (tmp_path / "metro.config.js").read_text()
    sd._rn_metro_autofix(tmp_path)
    twice = (tmp_path / "metro.config.js").read_text()
    assert once == twice
    assert twice.count("process.env.RCT_METRO_PORT") == 1


def test_rn_metro_autofix_injects_server_block_when_absent(tmp_path):
    (tmp_path / "metro.config.js").write_text(
        "const config = {\n"
        "  transformer: { babelTransformerPath: 'x' },\n"
        "  resolver: { sourceExts: ['svg'] },\n"
        "};\n"
        "module.exports = mergeConfig(defaultConfig, config);\n"
    )
    status, detail = sd._rn_metro_detect(tmp_path)
    assert status == "problem"
    assert "autofixable" in detail
    sd._rn_metro_autofix(tmp_path)
    text = (tmp_path / "metro.config.js").read_text()
    assert "server: {" in text
    assert "process.env.RCT_METRO_PORT" in text
    assert "|| 8081" in text
    assert sd._rn_metro_detect(tmp_path)[0] == "ok"


def test_rn_metro_autofix_adds_port_to_existing_server_block(tmp_path):
    (tmp_path / "metro.config.js").write_text(
        "module.exports = { server: { someOtherThing: 1 } };\n"
    )
    status, detail = sd._rn_metro_detect(tmp_path)
    assert status == "problem"
    assert "autofixable" in detail
    sd._rn_metro_autofix(tmp_path)
    text = (tmp_path / "metro.config.js").read_text()
    assert "process.env.RCT_METRO_PORT" in text
    assert "someOtherThing" in text
    assert sd._rn_metro_detect(tmp_path)[0] == "ok"


def test_rn_metro_autofix_noop_for_unrecognized_shape(tmp_path):
    text = "module.exports = makeMetroConfig(__dirname);\n"
    (tmp_path / "metro.config.js").write_text(text)
    sd._rn_metro_autofix(tmp_path)
    assert (tmp_path / "metro.config.js").read_text() == text
    assert sd._rn_metro_detect(tmp_path)[0] == "problem"


def test_rn_pkg_not_applicable_without_pkg(tmp_path):
    assert sd._rn_pkg_applies(tmp_path) is False


def test_rn_pkg_detect_ok_when_clean(tmp_path):
    (tmp_path / "package.json").write_text(
        json.dumps({"scripts": {"start": "react-native start", "ios": "react-native run-ios"}})
    )
    assert sd._rn_pkg_detect(tmp_path)[0] == "ok"


def test_rn_pkg_detect_problem_with_space_form(tmp_path):
    (tmp_path / "package.json").write_text(
        json.dumps({"scripts": {"start": "react-native start --port 8083"}})
    )
    status, detail = sd._rn_pkg_detect(tmp_path)
    assert status == "problem"
    assert "start" in detail


def test_rn_pkg_detect_problem_with_equals_form(tmp_path):
    (tmp_path / "package.json").write_text(
        json.dumps({"scripts": {"ios": "react-native run-ios --port=8083"}})
    )
    assert sd._rn_pkg_detect(tmp_path)[0] == "problem"


def test_rn_pkg_autofix_strips_port_flag(tmp_path):
    (tmp_path / "package.json").write_text(
        json.dumps(
            {
                "name": "x",
                "scripts": {
                    "android": "react-native run-android --port 8083",
                    "ios": "react-native run-ios --port 8083",
                    "start": "react-native start --port 8083",
                    "test": "jest",
                },
                "dependencies": {"react-native": "0.83"},
            },
            indent=2,
        )
    )
    sd._rn_pkg_autofix(tmp_path)
    data = json.loads((tmp_path / "package.json").read_text())
    assert data["scripts"]["start"] == "react-native start"
    assert data["scripts"]["ios"] == "react-native run-ios"
    assert data["scripts"]["android"] == "react-native run-android"
    assert data["scripts"]["test"] == "jest"
    assert data["dependencies"]["react-native"] == "0.83"
    assert sd._rn_pkg_detect(tmp_path)[0] == "ok"


def test_rn_pkg_autofix_idempotent(tmp_path):
    (tmp_path / "package.json").write_text(
        json.dumps({"scripts": {"start": "react-native start --port 8083"}})
    )
    sd._rn_pkg_autofix(tmp_path)
    once = (tmp_path / "package.json").read_text()
    sd._rn_pkg_autofix(tmp_path)
    twice = (tmp_path / "package.json").read_text()
    assert once == twice


def test_rn_pkg_targets_react_native_scripts_by_command(tmp_path):
    (tmp_path / "package.json").write_text(
        json.dumps({"scripts": {"dev": "react-native start --port 8083"}})
    )
    assert sd._rn_pkg_detect(tmp_path)[0] == "problem"
    sd._rn_pkg_autofix(tmp_path)
    assert (
        json.loads((tmp_path / "package.json").read_text())["scripts"]["dev"]
        == "react-native start"
    )


def test_rn_xcode_not_applicable_without_file(tmp_path):
    assert sd._rn_xcode_applies(tmp_path) is False


def test_rn_xcode_detect_problem_for_static_export(tmp_path):
    _make_ios(tmp_path, "export NODE_BINARY=node\nexport RCT_METRO_PORT=8083\n")
    status, detail = sd._rn_xcode_detect(tmp_path, "splashdown.env")
    assert status == "problem"
    assert "statically" in detail.lower()


def test_rn_xcode_detect_problem_when_missing(tmp_path):
    _make_ios(tmp_path, "export NODE_BINARY=node\n")
    assert sd._rn_xcode_detect(tmp_path, "splashdown.env")[0] == "problem"


def test_rn_xcode_detect_ok_with_block(tmp_path):
    _make_ios(tmp_path, "export NODE_BINARY=node\n" + sd._xcode_block("splashdown.env"))
    assert sd._rn_xcode_detect(tmp_path, "splashdown.env")[0] == "ok"


def test_rn_xcode_autofix_replaces_static(tmp_path):
    _make_ios(
        tmp_path,
        "# header\nexport NODE_BINARY=node\n\n# Pin Metro port\nexport RCT_METRO_PORT=8083\n",
    )
    sd._rn_xcode_autofix(tmp_path, "splashdown.env")
    text = (tmp_path / "ios" / ".xcode.env").read_text()
    assert "export RCT_METRO_PORT=8083" not in text
    assert "export NODE_BINARY=node" in text
    assert sd._XCODE_BEGIN in text
    assert sd._XCODE_END in text
    assert "splashdown.env" in text
    assert sd._rn_xcode_detect(tmp_path, "splashdown.env")[0] == "ok"


def test_rn_xcode_autofix_appends_when_missing(tmp_path):
    _make_ios(tmp_path, "export NODE_BINARY=node\n")
    sd._rn_xcode_autofix(tmp_path, "splashdown.env")
    text = (tmp_path / "ios" / ".xcode.env").read_text()
    assert "export NODE_BINARY=node" in text
    assert sd._XCODE_BEGIN in text


def test_rn_xcode_autofix_idempotent(tmp_path):
    _make_ios(tmp_path, "export NODE_BINARY=node\nexport RCT_METRO_PORT=8083\n")
    sd._rn_xcode_autofix(tmp_path, "splashdown.env")
    once = (tmp_path / "ios" / ".xcode.env").read_text()
    sd._rn_xcode_autofix(tmp_path, "splashdown.env")
    twice = (tmp_path / "ios" / ".xcode.env").read_text()
    assert once == twice
    assert twice.count(sd._XCODE_BEGIN) == 1
    assert twice.count(sd._XCODE_END) == 1


def test_rn_xcode_detect_ok_for_handwritten_splashdown_wiring(tmp_path):
    """A user-written, non-sentinel block that reads splashdown.env counts as ok."""
    _make_ios(
        tmp_path,
        (
            "export NODE_BINARY=node\n"
            'if [ -z "${RCT_METRO_PORT:-}" ] && [ -f "${SRCROOT}/../splashdown.env" ]; then\n'
            '  export RCT_METRO_PORT="$(grep \'^RCT_METRO_PORT=\' "${SRCROOT}/../splashdown.env" | cut -d= -f2)"\n'
            "fi\n"
            'export RCT_METRO_PORT="${RCT_METRO_PORT:-8083}"\n'
        ),
    )
    assert sd._rn_xcode_detect(tmp_path, "splashdown.env")[0] == "ok"


def _xcode_wiring_for(env_file: str) -> str:
    return (
        "export NODE_BINARY=node\n"
        f'if [ -z "${{RCT_METRO_PORT:-}}" ] && [ -f "${{SRCROOT}}/../{env_file}" ]; then\n'
        "  export RCT_METRO_PORT=\"$(grep '^RCT_METRO_PORT=' "
        f'"${{SRCROOT}}/../{env_file}" | cut -d= -f2)"\n'
        "fi\n"
    )


def test_wiring_destination_is_relative_to_the_directory_a_check_inspects(tmp_path):
    assert sd.wiring_destination(tmp_path, tmp_path, ".env") == ".env"
    assert (
        sd.wiring_destination(tmp_path / "apps" / "mobile", tmp_path, "splashdown.env")
        == "../../splashdown.env"
    )


def test_rn_xcode_autofix_injects_the_configured_destination(tmp_path):
    _make_ios(tmp_path, "export NODE_BINARY=node\n")

    sd._rn_xcode_autofix(tmp_path, "config/dev.env")

    text = (tmp_path / "ios" / ".xcode.env").read_text()
    assert "export NODE_BINARY=node" in text
    assert '"${SRCROOT}/../config/dev.env"' in text
    assert "splashdown.env" not in text
    assert sd._rn_xcode_detect(tmp_path, "config/dev.env")[0] == "ok"


def test_rn_xcode_detect_reports_a_block_naming_another_file(tmp_path):
    _make_ios(tmp_path, sd._xcode_block("splashdown.env"))

    status, detail = sd._rn_xcode_detect(tmp_path, ".env")

    assert status == "problem"
    assert ".env" in detail


def test_rn_xcode_autofix_repoints_its_own_block_at_the_new_destination(tmp_path):
    _make_ios(tmp_path, "export NODE_BINARY=node\n\n" + sd._xcode_block("splashdown.env"))

    sd._rn_xcode_autofix(tmp_path, ".env")

    text = (tmp_path / "ios" / ".xcode.env").read_text()
    assert text.count(sd._XCODE_BEGIN) == 1
    assert '"${SRCROOT}/../.env"' in text
    assert "splashdown.env" not in text
    assert "export NODE_BINARY=node" in text


def test_rn_xcode_detect_reports_handwritten_wiring_for_another_file(tmp_path):
    _make_ios(tmp_path, _xcode_wiring_for("other.env"))

    status, detail = sd._rn_xcode_detect(tmp_path, "splashdown.env")

    assert status == "problem"
    assert "other.env" in detail
    assert "splashdown.env" in detail


def test_rn_xcode_autofix_preserves_handwritten_wiring_it_cannot_repoint(tmp_path):
    content = _xcode_wiring_for("other.env")
    _make_ios(tmp_path, content)

    sd._rn_xcode_autofix(tmp_path, "splashdown.env")

    assert (tmp_path / "ios" / ".xcode.env").read_bytes() == content.encode()


def test_rn_xcode_keeps_working_wiring_for_a_custom_destination_byte_identical(tmp_path):
    content = _xcode_wiring_for("config/dev.env")
    _make_ios(tmp_path, content)
    assert sd._rn_xcode_detect(tmp_path, "config/dev.env")[0] == "ok"

    sd._rn_xcode_autofix(tmp_path, "config/dev.env")

    assert (tmp_path / "ios" / ".xcode.env").read_bytes() == content.encode()


def test_rn_xcode_detect_reports_a_reference_through_an_unknown_variable(tmp_path):
    _make_ios(tmp_path, 'export RCT_METRO_PORT="$(cat "$MY_ROOT/splashdown.env")"\n')

    status, detail = sd._rn_xcode_detect(tmp_path, "splashdown.env")

    assert status == "problem"
    assert "$MY_ROOT/splashdown.env" in detail


def test_rn_xcode_detect_ignores_a_dotenv_path_that_wires_nothing(tmp_path):
    _make_ios(tmp_path, 'export NODE_BINARY=node\nsource "${SRCROOT}/../splashdown.env"\n')

    status, detail = sd._rn_xcode_detect(tmp_path, "splashdown.env")

    assert status == "problem"
    assert detail == "ios/.xcode.env doesn't wire RCT_METRO_PORT to splashdown.env"


def test_rn_xcode_detect_ignores_a_dotenv_path_assigned_to_another_variable(tmp_path):
    _make_ios(tmp_path, 'export SOME_TOOL_ENV="${SRCROOT}/../.env"\n')

    status, detail = sd._rn_xcode_detect(tmp_path, ".env")

    assert status == "problem"
    assert detail == "ios/.xcode.env doesn't wire RCT_METRO_PORT to .env"


def test_rn_xcode_detect_ignores_a_release_only_port_wiring(tmp_path):
    _make_ios(
        tmp_path,
        'if [ "$CONFIGURATION" = Release ]; then\n'
        "  export RCT_METRO_PORT=\"$(grep '^RCT_METRO_PORT=' "
        '"${SRCROOT}/../splashdown.env" | cut -d= -f2)"\n'
        "fi\n",
    )

    status, detail = sd._rn_xcode_detect(tmp_path, "splashdown.env")

    assert status == "problem"
    assert detail == "ios/.xcode.env doesn't wire RCT_METRO_PORT to splashdown.env"


def test_rn_xcode_detect_ignores_react_native_config_envfile(tmp_path):
    _make_ios(tmp_path, "export ENVFILE=.env.staging\n")

    status, detail = sd._rn_xcode_detect(tmp_path, "splashdown.env")

    assert status == "problem"
    assert detail == "ios/.xcode.env doesn't wire RCT_METRO_PORT to splashdown.env"


def test_rn_xcode_autofix_wires_a_file_whose_dotenv_paths_wire_nothing(tmp_path):
    _make_ios(
        tmp_path,
        'export ENVFILE=.env.staging\nsource "${SRCROOT}/.xcode.env.local"\n',
    )

    sd._rn_xcode_autofix(tmp_path, "splashdown.env")

    text = (tmp_path / "ios" / ".xcode.env").read_text()
    assert "export ENVFILE=.env.staging" in text
    assert 'source "${SRCROOT}/.xcode.env.local"' in text
    assert sd._rn_xcode_detect(tmp_path, "splashdown.env")[0] == "ok"


def test_rn_xcode_detect_ignores_a_brace_default_path_outside_the_port_wiring(tmp_path):
    _make_ios(tmp_path, 'source "${SRCROOT:-.}/../splashdown.env"\n')

    status, detail = sd._rn_xcode_detect(tmp_path, "splashdown.env")

    assert status == "problem"
    assert detail == "ios/.xcode.env doesn't wire RCT_METRO_PORT to splashdown.env"


def test_rn_xcode_autofix_wires_past_a_brace_default_path(tmp_path):
    _make_ios(tmp_path, 'source "${SRCROOT:-.}/../shared.env"\n')

    sd._rn_xcode_autofix(tmp_path, "splashdown.env")

    text = (tmp_path / "ios" / ".xcode.env").read_text()
    assert 'source "${SRCROOT:-.}/../shared.env"' in text
    assert sd._rn_xcode_detect(tmp_path, "splashdown.env")[0] == "ok"


def test_rn_xcode_detect_names_only_the_path_the_port_wiring_reads(tmp_path):
    _make_ios(tmp_path, "export ENVFILE=.env.staging\n" + _xcode_wiring_for("other.env"))

    status, detail = sd._rn_xcode_detect(tmp_path, "splashdown.env")

    assert status == "problem"
    assert detail == (
        "ios/.xcode.env reads ${SRCROOT}/../other.env, not the configured splashdown.env"
    )


def test_rn_xcode_autofix_repairs_its_own_block_missing_the_closing_sentinel(tmp_path):
    truncated = sd._xcode_block("splashdown.env").replace(sd._XCODE_END + "\n", "")
    _make_ios(tmp_path, "export NODE_BINARY=node\n\n" + truncated)

    sd._rn_xcode_autofix(tmp_path, ".env")

    text = (tmp_path / "ios" / ".xcode.env").read_text()
    assert "export NODE_BINARY=node" in text
    assert "splashdown.env" not in text
    assert text.count(sd._XCODE_BEGIN) == 1
    assert text.count(sd._XCODE_END) == 1
    assert sd._rn_xcode_detect(tmp_path, ".env")[0] == "ok"


def test_rn_xcode_manual_instructions_name_the_configured_destination(tmp_path):
    instructions = sd.wiring._rn_xcode_manual(tmp_path, ".env")

    assert '"${SRCROOT}/../.env"' in instructions
    assert "splashdown.env" not in instructions


def test_rn_wiring_checks_bind_the_destination_to_the_xcode_check(tmp_path):
    _make_ios(tmp_path, "export NODE_BINARY=node\n")
    check = next(c for c in sd.rn_wiring_checks(".env") if c.id == "rn-xcode-env")

    assert ".env" in check.description
    assert check.detect(tmp_path)[0] == "problem"
    check.autofix(tmp_path)
    assert check.detect(tmp_path)[0] == "ok"
    assert check.files(tmp_path) == (tmp_path / "ios" / ".xcode.env",)


def test_doctor_checks_the_xcode_wiring_against_the_recipe_destination(tmp_path, capsys):
    (tmp_path / "package.json").write_text(_RN_PACKAGE_JSON)
    _make_ios(tmp_path, _xcode_wiring_for(".env"))
    (tmp_path / "splashdown.toml").write_text(
        '[project]\nframework = "react-native"\nenv_file = ".env"\n'
    )

    sd.cmd_doctor(tmp_path)

    assert "rn-xcode-env: ios/.xcode.env wires RCT_METRO_PORT to .env" in capsys.readouterr().err


def test_doctor_reports_xcode_wiring_that_does_not_name_the_recipe_destination(tmp_path, capsys):
    (tmp_path / "package.json").write_text(_RN_PACKAGE_JSON)
    _make_ios(tmp_path, _xcode_wiring_for("splashdown.env"))
    (tmp_path / "splashdown.toml").write_text(
        '[project]\nframework = "react-native"\nenv_file = ".env"\n'
    )

    assert sd.cmd_doctor(tmp_path) == 1
    err = capsys.readouterr().err
    assert "rn-xcode-env: ios/.xcode.env reads ${SRCROOT}/../splashdown.env" in err
    assert "not the configured .env" in err


def test_rn_xcode_autofix_exports_the_port_a_bare_sourcing_leaves_unset(tmp_path):
    # `.` sets RCT_METRO_PORT in the sourcing shell without exporting it, so the
    # Xcode build never sees the value. Naming the file is not wiring.
    content = (
        "export NODE_BINARY=node\n"
        'if [ -f "${SRCROOT}/../splashdown.env" ]; then\n'
        '  . "${SRCROOT}/../splashdown.env"\n'
        "fi\n"
    )
    _make_ios(tmp_path, content)

    sd._rn_xcode_autofix(tmp_path, "splashdown.env")

    text = (tmp_path / "ios" / ".xcode.env").read_text()
    assert content in text
    assert 'export RCT_METRO_PORT="${RCT_METRO_PORT:-8083}"' in text
    assert sd._rn_xcode_detect(tmp_path, "splashdown.env")[0] == "ok"


def test_cmd_init_scanned_rn_wires_everything(tmp_path):
    _git_init(tmp_path)
    (tmp_path / "package.json").write_text(
        json.dumps(
            {
                "scripts": {
                    "start": "react-native start --port 8083",
                    "ios": "react-native run-ios --port 8083",
                },
                "dependencies": {"react-native": "0.83"},
                "devDependencies": {"lefthook": "^1.0"},
            },
            indent=2,
        )
    )
    (tmp_path / "metro.config.js").write_text(
        "const config = { server: { port: 8083 } };\nmodule.exports = config;\n"
    )
    (tmp_path / "ios").mkdir()
    (tmp_path / "ios" / ".xcode.env").write_text(
        "export NODE_BINARY=node\nexport RCT_METRO_PORT=8083\n"
    )
    (tmp_path / "lefthook.yml").write_text(
        "pre-commit:\n  commands:\n    lint:\n      run: echo lint\n"
    )
    # Run init — should scaffold + wire. Force mise so the loader-wiring leg is
    # exercised (the repo has no loader config, so detection now yields "none").
    sd.cmd_init(tmp_path, loader_override="mise")
    assert (tmp_path / "splashdown.toml").exists()
    assert (tmp_path / "splashdown.local.toml").exists()
    assert (tmp_path / "mise.toml").exists()
    pkg = json.loads((tmp_path / "package.json").read_text())
    assert "--port" not in pkg["scripts"]["start"]
    assert "process.env.RCT_METRO_PORT" in (tmp_path / "metro.config.js").read_text()
    assert sd._XCODE_BEGIN in (tmp_path / "ios" / ".xcode.env").read_text()
    assert "post-checkout:" in (tmp_path / "lefthook.yml").read_text()
    # core.hooksPath NOT set (lefthook owns hooks).
    import subprocess as _sp

    r = _sp.run(
        ["git", "-C", str(tmp_path), "config", "--get", "core.hooksPath"], capture_output=True
    )
    assert r.returncode != 0 or not r.stdout.strip()
    assert sd.cmd_doctor(tmp_path) == 0


def test_doctor_fix_full_rn_project(tmp_path):
    _git_init(tmp_path)
    (tmp_path / "package.json").write_text(
        json.dumps(
            {
                "scripts": {
                    "start": "react-native start --port 8083",
                    "ios": "react-native run-ios --port 8083",
                    "android": "react-native run-android --port 8083",
                },
                "dependencies": {"react-native": "0.83"},
                "devDependencies": {"lefthook": "^1.0"},
            },
            indent=2,
        )
    )
    (tmp_path / "metro.config.js").write_text(
        "const config = {\n  server: {\n    port: 8083,\n  },\n};\nmodule.exports = config;\n"
    )
    (tmp_path / "ios").mkdir()
    (tmp_path / "ios" / ".xcode.env").write_text(
        "export NODE_BINARY=node\nexport RCT_METRO_PORT=8083\n"
    )
    (tmp_path / "lefthook.yml").write_text(
        "pre-commit:\n  commands:\n    lint:\n      run: echo lint\n"
    )
    assert sd.cmd_doctor(tmp_path) == 1
    assert sd.cmd_doctor(tmp_path, fix=True) == 0
    assert sd.cmd_doctor(tmp_path) == 0
    pkg = json.loads((tmp_path / "package.json").read_text())
    for name in ("start", "ios", "android"):
        assert "--port" not in pkg["scripts"][name]
    assert "process.env.RCT_METRO_PORT" in (tmp_path / "metro.config.js").read_text()
    assert sd._XCODE_BEGIN in (tmp_path / "ios" / ".xcode.env").read_text()
    lh = (tmp_path / "lefthook.yml").read_text()
    assert "post-checkout:" in lh
    assert "splashdown:" in lh
    assert "lint:" in lh


def test_app_inventory_is_dataclass_with_name_path_profile(tmp_path):
    app = sd.AppInventory(name="api", path=tmp_path / "apps" / "api", profile="node-backend")
    assert app.name == "api"
    assert app.profile == "node-backend"
    assert app.path == tmp_path / "apps" / "api"


def test_project_inventory_collects_apps_and_loader(tmp_path):
    inv = sd.ProjectInventory(
        workspace="pnpm",
        apps=[sd.AppInventory(name="api", path=tmp_path / "apps/api", profile="node-backend")],
        loader="mise",
    )
    assert inv.workspace == "pnpm"
    assert inv.loader == "mise"
    assert len(inv.apps) == 1


def test_detect_workspace_pnpm(tmp_path):
    (tmp_path / "pnpm-workspace.yaml").write_text("packages:\n  - apps/*\n")
    assert sd._detect_workspace(tmp_path) == "pnpm"


def test_detect_workspace_yarn(tmp_path):
    (tmp_path / "package.json").write_text('{"workspaces": ["apps/*"]}')
    (tmp_path / "yarn.lock").write_text("")
    assert sd._detect_workspace(tmp_path) == "yarn"


def test_detect_workspace_npm(tmp_path):
    (tmp_path / "package.json").write_text('{"workspaces": ["apps/*"]}')
    (tmp_path / "package-lock.json").write_text("")
    assert sd._detect_workspace(tmp_path) == "npm"


def test_detect_workspace_cargo(tmp_path):
    (tmp_path / "Cargo.toml").write_text('[workspace]\nmembers = ["crates/*"]\n')
    assert sd._detect_workspace(tmp_path) == "cargo"


def test_detect_workspace_gradle(tmp_path):
    (tmp_path / "settings.gradle.kts").write_text('include("api", "web")\n')
    assert sd._detect_workspace(tmp_path) == "gradle"


def test_detect_workspace_single(tmp_path):
    assert sd._detect_workspace(tmp_path) == "single"


def test_scanner_single_app_no_workspace(tmp_path):
    (tmp_path / "package.json").write_text('{"name": "single"}')
    inv = sd.Scanner().scan(tmp_path)
    assert inv.workspace == "single"
    assert len(inv.apps) == 1
    assert inv.apps[0].name == "main"
    assert inv.apps[0].path == tmp_path
    assert inv.apps[0].profile == "unknown"  # no profile matches this fixture


def test_scanner_pnpm_monorepo_enumerates_apps(tmp_path):
    (tmp_path / "pnpm-workspace.yaml").write_text("packages:\n  - apps/*\n")
    (tmp_path / "apps").mkdir()
    (tmp_path / "apps" / "api").mkdir()
    # Give api a detectable framework so it isn't dropped as unknown.
    (tmp_path / "apps" / "api" / "package.json").write_text('{"dependencies": {"hono": "^4.0.0"}}')
    (tmp_path / "apps" / "web").mkdir()
    # Give web a detectable framework so it isn't dropped as unknown.
    (tmp_path / "apps" / "web" / "vite.config.ts").write_text("export default {}")
    inv = sd.Scanner().scan(tmp_path)
    assert inv.workspace == "pnpm"
    names = sorted(a.name for a in inv.apps)
    assert names == ["api", "web"]


def test_scanner_loader_defaults_to_none(tmp_path):
    inv = sd.Scanner().scan(tmp_path)
    assert inv.loader == "none"


def test_select_loader_reports_no_configuration(tmp_path):
    selection = sd.select_loader(tmp_path)
    assert (selection.name, selection.selected_by) == ("none", "unconfigured")
    assert selection.reason == "no loader configuration found"


def test_select_loader_never_probes_path_for_an_unconfigured_checkout(tmp_path, monkeypatch):
    monkeypatch.setattr(shutil, "which", lambda name: pytest.fail(f"probed PATH for {name}"))
    assert sd.select_loader(tmp_path).name == "none"
    assert sd.Scanner().scan(tmp_path).loader == "none"


def test_select_loader_reports_the_detected_configuration(tmp_path):
    (tmp_path / ".envrc").write_text("")
    selection = sd.select_loader(tmp_path)
    assert (selection.name, selection.selected_by) == ("direnv", "detected")
    assert selection.reason == "detected .envrc"


def test_select_loader_counts_both_mise_files_as_one_candidate(tmp_path):
    (tmp_path / "mise.toml").write_text("")
    (tmp_path / ".mise.toml").write_text("")
    selection = sd.select_loader(tmp_path)
    assert selection.name == "mise"
    assert selection.configs == ("mise.toml", ".mise.toml")


def test_select_loader_override_wins_over_a_detected_loader(tmp_path):
    (tmp_path / ".envrc").write_text("")
    selection = sd.select_loader(tmp_path, "mise")
    assert (selection.name, selection.selected_by) == ("mise", "override")
    assert selection.reason == "--loader mise"


def test_select_loader_override_none_opts_out_of_a_detected_loader(tmp_path):
    (tmp_path / "mise.toml").write_text("")
    assert sd.select_loader(tmp_path, "none").name == "none"


def test_select_loader_rejects_several_configured_loaders(tmp_path):
    (tmp_path / "mise.toml").write_text("")
    (tmp_path / ".envrc").write_text("")
    with pytest.raises(sd.UsageError) as error:
        sd.select_loader(tmp_path)
    assert "direnv, mise" in str(error.value)
    assert "--loader" in str(error.value)


def test_cmd_init_fails_before_writing_when_several_loaders_are_configured(tmp_path):
    (tmp_path / "vite.config.ts").write_text("export default {}")
    (tmp_path / "mise.toml").write_text("")
    (tmp_path / ".envrc").write_text("")
    before = sorted(p.name for p in tmp_path.iterdir())
    with pytest.raises(sd.UsageError):
        sd.cmd_init(tmp_path)
    assert sorted(p.name for p in tmp_path.iterdir()) == before
    assert (tmp_path / "mise.toml").read_text() == ""
    assert (tmp_path / ".envrc").read_text() == ""


def test_cmd_init_leaves_an_uninstalled_project_on_the_none_loader(tmp_path):
    (tmp_path / "vite.config.ts").write_text("export default {}")
    sd.cmd_init(tmp_path)
    assert 'loader = "none"' in (tmp_path / "splashdown.toml").read_text()
    assert not (tmp_path / "mise.toml").exists()


def test_cmd_init_loader_none_opts_out_of_a_configured_loader(tmp_path):
    (tmp_path / "vite.config.ts").write_text("export default {}")
    (tmp_path / "mise.toml").write_text("")
    sd.cmd_init(tmp_path, loader_override="none")
    assert 'loader = "none"' in (tmp_path / "splashdown.toml").read_text()
    assert (tmp_path / "mise.toml").read_text() == ""


def test_scanner_detects_mise_loader(tmp_path):
    (tmp_path / "mise.toml").write_text("")
    inv = sd.Scanner().scan(tmp_path)
    assert inv.loader == "mise"


def test_scanner_detects_direnv_loader(tmp_path):
    (tmp_path / ".envrc").write_text("")
    inv = sd.Scanner().scan(tmp_path)
    assert inv.loader == "direnv"


def test_scanner_detects_devbox_loader(tmp_path):
    (tmp_path / "devbox.json").write_text("{}")
    inv = sd.Scanner().scan(tmp_path)
    assert inv.loader == "devbox"


def test_scanner_scan_uses_an_explicit_loader_without_reselecting(tmp_path):
    (tmp_path / "mise.toml").write_text("")
    (tmp_path / ".envrc").write_text("")
    assert sd.Scanner().scan(tmp_path, loader="direnv").loader == "direnv"


def _git_ignores(cwd: Path, relpath: str) -> bool:
    return (
        subprocess.run(
            ["git", "check-ignore", "-q", "--no-index", "--", relpath],
            cwd=cwd,
            check=False,
        ).returncode
        == 0
    )


def _tracked_files(cwd: Path) -> list[str]:
    return subprocess.check_output(["git", "ls-files"], cwd=cwd, text=True).split()


def _block(*rules: str) -> str:
    return "\n".join([sd.hooks.GITIGNORE_BEGIN, *rules, sd.hooks.GITIGNORE_END, ""])


def test_gitignore_rule_anchors_and_escapes_a_literal_path():
    assert sd.hooks.gitignore_rule("splashdown.env") == "/splashdown.env"
    assert sd.hooks.gitignore_rule("apps/api/.env") == "/apps/api/.env"
    assert sd.hooks.gitignore_rule("env[a]*?.env") == "/env\\[a\\]\\*\\?.env"
    assert sd.hooks.gitignore_rule("trailing .env ") == "/trailing .env\\ "
    assert sd.hooks.gitignore_rule("#hash!.env") == "/\\#hash!.env"


def test_gitignore_rule_path_round_trips_an_escaped_rule():
    for relpath in ("splashdown.env", "apps/api/.env", "env[a]*?.env", "trailing .env "):
        assert sd.hooks.gitignore_rule_path(sd.hooks.gitignore_rule(relpath)) == relpath


def test_ensure_gitignore_writes_the_marked_block(tmp_path):
    _git_init(tmp_path)
    sd._ensure_gitignore(tmp_path, ["splashdown.env"])
    assert (tmp_path / ".gitignore").read_text() == _block(
        "/splashdown.local.toml", "/splashdown.env"
    )


def test_ensure_gitignore_is_idempotent(tmp_path):
    _git_init(tmp_path)
    sd._ensure_gitignore(tmp_path, ["splashdown.env"])
    first = (tmp_path / ".gitignore").read_text()
    sd._ensure_gitignore(tmp_path, ["splashdown.env"])
    assert (tmp_path / ".gitignore").read_text() == first


def test_ensure_gitignore_reuses_an_effective_user_rule(tmp_path):
    _git_init(tmp_path)
    (tmp_path / ".gitignore").write_text("*.env\n")
    sd._ensure_gitignore(tmp_path, ["splashdown.env"])
    assert (tmp_path / ".gitignore").read_text() == "*.env\n\n" + _block("/splashdown.local.toml")


def test_ensure_gitignore_keeps_unrelated_lines_and_comments(tmp_path):
    _git_init(tmp_path)
    (tmp_path / ".gitignore").write_text("# build output\ndist/\nnode_modules\n")
    sd._ensure_gitignore(tmp_path, ["splashdown.env"])
    text = (tmp_path / ".gitignore").read_text()
    assert text.startswith("# build output\ndist/\nnode_modules\n")
    assert text.endswith(_block("/splashdown.local.toml", "/splashdown.env"))


def test_ensure_gitignore_escapes_a_destination_holding_glob_characters(tmp_path):
    _git_init(tmp_path)
    sd._ensure_gitignore(tmp_path, ["env[dev].env"])
    assert "/env\\[dev\\].env" in (tmp_path / ".gitignore").read_text()
    (tmp_path / "env[dev].env").write_text("PORT=1\n")
    (tmp_path / "envd.env").write_text("PORT=1\n")
    assert _git_ignores(tmp_path, "env[dev].env")
    assert not _git_ignores(tmp_path, "envd.env")


def test_ensure_gitignore_anchors_a_nested_destination(tmp_path):
    _git_init(tmp_path)
    (tmp_path / "apps" / "api").mkdir(parents=True)
    sd._ensure_gitignore(tmp_path, ["apps/api/.env"])
    assert "/apps/api/.env" in (tmp_path / ".gitignore").read_text()
    assert _git_ignores(tmp_path, "apps/api/.env")
    assert not _git_ignores(tmp_path, ".env")


def test_ensure_gitignore_leaves_duplicate_markers_alone(tmp_path, capsys):
    _git_init(tmp_path)
    original = _block("/splashdown.local.toml") + _block("/splashdown.env")
    (tmp_path / ".gitignore").write_text(original)
    sd._ensure_gitignore(tmp_path, ["splashdown.env"])
    assert (tmp_path / ".gitignore").read_text() == original
    assert "left .gitignore alone" in capsys.readouterr().err


def test_ensure_gitignore_leaves_an_unclosed_marker_alone(tmp_path, capsys):
    _git_init(tmp_path)
    original = sd.hooks.GITIGNORE_BEGIN + "\n/splashdown.env\n"
    (tmp_path / ".gitignore").write_text(original)
    sd._ensure_gitignore(tmp_path, ["splashdown.env"])
    assert (tmp_path / ".gitignore").read_text() == original
    assert "left .gitignore alone" in capsys.readouterr().err


def test_ensure_gitignore_reports_a_path_a_later_negation_keeps_visible(tmp_path, capsys):
    _git_init(tmp_path)
    original = _block("/splashdown.local.toml", "/splashdown.env") + "!/splashdown.env\n"
    (tmp_path / ".gitignore").write_text(original)
    sd._ensure_gitignore(tmp_path, ["splashdown.env"])
    err = capsys.readouterr().err
    assert "splashdown.env is still not ignored" in err
    assert "!/splashdown.env" in err
    assert (tmp_path / ".gitignore").read_text() == original


def test_ensure_gitignore_reports_a_tracked_destination(tmp_path, capsys):
    _git_init(tmp_path)
    (tmp_path / "splashdown.env").write_text("PORT=1\n")
    subprocess.run(["git", "add", "splashdown.env"], cwd=tmp_path, check=True)
    sd._ensure_gitignore(tmp_path, ["splashdown.env"])
    err = capsys.readouterr().err
    assert "splashdown.env is tracked by git" in err
    assert "git rm --cached splashdown.env" in err
    assert _tracked_files(tmp_path) == ["splashdown.env"]


def test_ensure_gitignore_reports_that_git_could_not_answer(tmp_path, capsys):
    sd._ensure_gitignore(tmp_path, ["splashdown.env"])
    assert "not a git repository" in capsys.readouterr().err
    assert (tmp_path / ".gitignore").read_text() == _block(
        "/splashdown.local.toml", "/splashdown.env"
    )


def test_ensure_gitignore_refuses_a_symlinked_gitignore(tmp_path, capsys):
    _git_init(tmp_path)
    (tmp_path / "elsewhere").write_text("")
    (tmp_path / ".gitignore").symlink_to(tmp_path / "elsewhere")
    sd._ensure_gitignore(tmp_path, ["splashdown.env"])
    assert "left .gitignore alone" in capsys.readouterr().err
    assert (tmp_path / "elsewhere").read_text() == ""


def test_revert_gitignore_removes_only_the_managed_block(tmp_path):
    (tmp_path / ".gitignore").write_text(
        "node_modules\nsplashdown.env\n*.log\n\n"
        + _block("/splashdown.local.toml", "/splashdown.env")
    )
    sd._revert_gitignore(tmp_path)
    text = (tmp_path / ".gitignore").read_text()
    assert text == "node_modules\nsplashdown.env\n*.log\n"


def test_revert_gitignore_keeps_the_rule_for_a_retained_file(tmp_path):
    (tmp_path / ".gitignore").write_text(_block("/splashdown.local.toml", "/splashdown.env"))
    (tmp_path / "splashdown.local.toml").write_text("[settings]\nprefix_match = false\n")
    sd._revert_gitignore(tmp_path)
    assert (tmp_path / ".gitignore").read_text() == _block("/splashdown.local.toml")


def test_revert_gitignore_removes_an_untracked_file_left_with_nothing(tmp_path):
    _git_init(tmp_path)
    (tmp_path / ".gitignore").write_text(_block("/splashdown.local.toml", "/splashdown.env"))
    sd._revert_gitignore(tmp_path)
    assert not (tmp_path / ".gitignore").exists()


def test_revert_gitignore_keeps_a_tracked_file_left_with_nothing(tmp_path):
    _git_init(tmp_path)
    (tmp_path / ".gitignore").write_text(_block("/splashdown.local.toml", "/splashdown.env"))
    subprocess.run(["git", "add", ".gitignore"], cwd=tmp_path, check=True)
    sd._revert_gitignore(tmp_path)
    assert (tmp_path / ".gitignore").read_text() == ""
    assert _tracked_files(tmp_path) == [".gitignore"]


def test_revert_gitignore_keeps_a_file_left_with_nothing_when_git_cannot_answer(tmp_path):
    (tmp_path / ".gitignore").write_text(_block("/splashdown.local.toml", "/splashdown.env"))
    sd._revert_gitignore(tmp_path)
    assert (tmp_path / ".gitignore").read_text() == ""


def test_revert_gitignore_keeps_a_file_that_still_has_user_rules(tmp_path):
    (tmp_path / ".gitignore").write_text(
        "node_modules/\n" + _block("/splashdown.local.toml", "/splashdown.env")
    )
    sd._revert_gitignore(tmp_path)
    assert (tmp_path / ".gitignore").read_text() == "node_modules/\n"


def test_revert_gitignore_noop_when_absent(tmp_path):
    sd._revert_gitignore(tmp_path)
    assert not (tmp_path / ".gitignore").exists()


def test_revert_gitignore_leaves_an_unmarked_file_alone(tmp_path):
    original = "splashdown.env\nsplashdown.local.toml\n"
    (tmp_path / ".gitignore").write_text(original)
    sd._revert_gitignore(tmp_path)
    assert (tmp_path / ".gitignore").read_text() == original


def test_doctor_runs_compose_check_alongside_the_framework(tmp_path, capsys):
    # A compose file is project-level: the check runs at the repo root whatever
    # framework resolved, and its problem is enough to fail the run.
    (tmp_path / "astro.config.mjs").write_text(
        "export default { server: { port: Number(process.env.WEB_DEV_PORT) || 4321 } };\n"
    )
    (tmp_path / "compose.yaml").write_text(
        'services:\n  db:\n    image: postgres:16\n    ports:\n      - "5432:5432"\n'
    )
    assert sd.cmd_doctor(tmp_path) == 1
    err = capsys.readouterr().err
    assert "astro-config-port" in err
    assert "compose-hardcoded-ports" in err


def test_doctor_compose_check_runs_without_any_framework_checks(tmp_path, capsys):
    # nextjs is env-only and contributes no checks, but a compose problem must
    # still be reported rather than swallowed by the "nothing to check" branch.
    (tmp_path / "compose.yaml").write_text('services:\n  db:\n    ports:\n      - "5432:5432"\n')
    assert sd.cmd_doctor(tmp_path, framework_override="nextjs") == 1
    err = capsys.readouterr().err
    assert "compose-hardcoded-ports" in err
    assert "no wiring checks needed" not in err


def test_doctor_compose_check_runs_at_root_for_a_subdirectory_app(tmp_path, capsys):
    app = tmp_path / "apps" / "web"
    app.mkdir(parents=True)
    (app / "astro.config.mjs").write_text("export default {};\n")
    (tmp_path / "compose.yaml").write_text('services:\n  db:\n    ports:\n      - "5432:5432"\n')
    (tmp_path / "splashdown.toml").write_text(
        '[apps.web]\npath = "apps/web"\nprofile = "astro"\nresources = []\n'
    )
    assert sd.cmd_doctor(tmp_path) == 1
    err = capsys.readouterr().err
    assert "compose-hardcoded-ports" in err
    assert "not applicable" not in err


def test_cmd_init_emits_compose_project_name(tmp_path):
    (tmp_path / "compose.yaml").write_text("services:\n  db:\n    image: postgres:16\n")
    (tmp_path / "astro.config.mjs").write_text("export default {};\n")
    sd.cmd_init(tmp_path)
    recipe = sd.Recipe.load(tmp_path / sd.RECIPE_NAME)
    assert "COMPOSE_PROJECT_NAME" in recipe.resources
    assert recipe.apps["main"]["profile"] == "astro"


def test_cmd_init_without_compose_emits_no_compose_resource(tmp_path):
    (tmp_path / "astro.config.mjs").write_text("export default {};\n")
    sd.cmd_init(tmp_path)
    recipe = sd.Recipe.load(tmp_path / sd.RECIPE_NAME)
    assert "COMPOSE_PROJECT_NAME" not in recipe.resources


def test_rn_metro_detect_ignores_commented_out_wiring(tmp_path):
    (tmp_path / "metro.config.js").write_text(
        "// server: { port: Number(process.env.RCT_METRO_PORT) }\n"
        "module.exports = { server: { port: 8083 } };\n"
    )
    status, detail = sd._rn_metro_detect(tmp_path)
    assert status == "problem"
    assert "autofixable" in detail


def test_rn_xcode_detect_ignores_a_commented_out_reference(tmp_path):
    (tmp_path / "ios").mkdir()
    (tmp_path / "ios" / ".xcode.env").write_text(
        "# source ../splashdown.env\nexport RCT_METRO_PORT=8083\n"
    )
    status, detail = sd._rn_xcode_detect(tmp_path, "splashdown.env")
    assert status == "problem"
    assert "literal" in detail


def test_vite_checks_ignore_commented_out_wiring(tmp_path):
    (tmp_path / "vite.config.ts").write_text(
        "/* server: { port: Number(process.env.WEB_DEV_PORT) } */\nexport default {};\n"
    )
    app = sd.AppInventory(name="web", path=tmp_path, profile="vite")
    check = next(
        c
        for c in sd.PROFILES["vite"].wiring_checks(app, "splashdown.env")
        if c.id == "vite-port-wired"
    )
    assert check.detect(tmp_path)[0] == "problem"


def test_astro_check_ignores_commented_out_wiring(tmp_path):
    (tmp_path / "astro.config.mjs").write_text(
        "// port: process.env.WEB_DEV_PORT\nexport default defineConfig({});\n"
    )
    app = sd.AppInventory(name="web", path=tmp_path, profile="astro")
    check = next(
        c
        for c in sd.PROFILES["astro"].wiring_checks(app, "splashdown.env")
        if c.id == "astro-config-port"
    )
    assert check.detect(tmp_path)[0] == "problem"


def test_doctor_reports_a_raising_check_instead_of_crashing(tmp_path, capsys, monkeypatch):
    # A detect() that blows up must cost one ✗, not the whole run.
    def boom(cwd):
        raise OSError("permission denied")

    (tmp_path / "metro.config.js").write_text("module.exports = {};\n")
    broken = sd.WiringCheck(
        id="boom",
        description="always raises",
        applies=lambda cwd: True,
        detect=boom,
        autofix=None,
        manual_instructions=None,
    )
    monkeypatch.setattr(sd.doctor, "_wiring_checks_for_framework", lambda f, c, e: [broken])
    rc = sd.cmd_doctor(tmp_path, framework_override="react-native", fix=False)
    err = capsys.readouterr().err
    assert rc != 0
    assert "boom" in err
    assert "permission denied" in err


def test_strip_js_comments_recovers_after_a_regex_literal(tmp_path):
    # A quote inside a regex character class opened a string that never closed, so
    # the whole rest of the file went unstripped and commented-out wiring counted.
    (tmp_path / "metro.config.js").write_text(
        'const strip = (s) => s.replace(/[\'"]/g, "");\n'
        "// server: { port: Number(process.env.RCT_METRO_PORT) }\n"
        "module.exports = { server: { port: 8081 } };\n"
    )
    status, detail = sd._rn_metro_detect(tmp_path)
    assert status == "problem"
    assert "autofixable" in detail


def test_strip_js_comments_keeps_an_escaped_slash_out_of_comment_detection(tmp_path):
    (tmp_path / "metro.config.js").write_text(
        "const re = /https:\\/\\//; module.exports = "
        "{ server: { port: Number(process.env.RCT_METRO_PORT) } };\n"
    )
    assert sd._rn_metro_detect(tmp_path)[0] == "ok"


def test_strip_js_comments_keeps_multiline_template_literals(tmp_path):
    (tmp_path / "vite.config.ts").write_text(
        "const banner = `line one\nline two`;\n"
        "export default { server: { port: Number(process.env.WEB_DEV_PORT) } };\n"
    )
    app = sd.AppInventory(name="web", path=tmp_path, profile="vite")
    check = next(
        c
        for c in sd.PROFILES["vite"].wiring_checks(app, "splashdown.env")
        if c.id == "vite-port-wired"
    )
    assert check.detect(tmp_path)[0] == "ok"


def test_rn_hook_detect_ignores_a_commented_out_lefthook_block(tmp_path):
    # Lefthook scaffolds a config that is mostly commented-out examples, and a hook
    # that never fires is the root cause of stale registry entries.
    _git_init(tmp_path)
    (tmp_path / "lefthook.yml").write_text(
        "# post-checkout:\n#   commands:\n#     splashdown:\n#       run: splash\n"
        "pre-commit:\n  commands: {}\n"
    )
    assert sd._rn_hook_detect(tmp_path)[0] == "problem"


def test_rn_hook_detect_ignores_a_commented_out_husky_hook(tmp_path):
    _git_init(tmp_path)
    (tmp_path / ".husky").mkdir()
    (tmp_path / ".husky" / "post-checkout").write_text("#!/bin/sh\n# splash\n")
    assert sd._rn_hook_detect(tmp_path)[0] == "problem"


_RN_PACKAGE_JSON = '{"dependencies":{"react-native":"0.83"}}'


def _nested_mobile_project(tmp_path: Path) -> tuple[Path, Path]:
    root = tmp_path / "repo"
    nested = root / "apps" / "mobile"
    nested.mkdir(parents=True)
    _git_init(root)
    (nested / "package.json").write_text(_RN_PACKAGE_JSON)
    return root, nested


def test_cmd_init_leaves_native_hook_uninstalled_for_a_mobile_project(tmp_path, capsys):
    _git_init(tmp_path)
    (tmp_path / "package.json").write_text(_RN_PACKAGE_JSON)

    sd.cmd_init(tmp_path)

    assert not _native_hook(tmp_path).exists()
    assert "installed by `splash trust`" in capsys.readouterr().err


def test_cmd_init_does_not_install_lefthook_for_a_mobile_project(tmp_path, monkeypatch):
    installs = _record_manager_installs(monkeypatch)
    _root, nested = _nested_mobile_project(tmp_path)
    (nested / "lefthook.yml").write_text("")

    sd.cmd_init(nested)

    assert installs == []


def test_cmd_init_nested_mobile_project_leaves_worktree_root_hook_uninstalled(tmp_path):
    root, nested = _nested_mobile_project(tmp_path)

    sd.cmd_init(nested)

    assert not (root / ".git" / "hooks" / "post-checkout").exists()


def test_doctor_fix_leaves_worktree_root_hook_uninstalled_from_a_nested_project(tmp_path):
    root, nested = _nested_mobile_project(tmp_path)
    sd.cmd_init(nested)

    sd.cmd_doctor(nested, fix=True)

    assert not (root / ".git" / "hooks" / "post-checkout").exists()


def test_doctor_reports_the_hook_check_inapplicable_in_a_nested_project(tmp_path, capsys):
    _root, nested = _nested_mobile_project(tmp_path)
    sd.cmd_init(nested)
    capsys.readouterr()

    sd.cmd_doctor(nested)

    err = capsys.readouterr().err
    assert "hook: not applicable" in err
    assert "splash doctor --fix" not in err


def test_configure_hook_writes_pre_commit_config(tmp_path):
    (tmp_path / ".pre-commit-config.yaml").write_text("repos:\n  - repo: local\n    hooks:\n")

    sd._configure_post_checkout_hook(tmp_path)

    text = (tmp_path / ".pre-commit-config.yaml").read_text()
    assert "- id: splashdown" in text
    assert "$PRE_COMMIT_CHECKOUT_TYPE" in text


def test_configure_hook_writes_prek_config(tmp_path):
    (tmp_path / "prek.toml").write_text("")

    sd._configure_post_checkout_hook(tmp_path)

    assert 'id = "splashdown"' in (tmp_path / "prek.toml").read_text()


def test_configure_hook_writes_simple_git_hooks_config(tmp_path):
    (tmp_path / ".simple-git-hooks.json").write_text("{}")

    sd._configure_post_checkout_hook(tmp_path)

    text = (tmp_path / ".simple-git-hooks.json").read_text()
    assert "post-checkout" in text
    assert "hook post-checkout" in text


def test_configure_hook_preserves_an_overcommit_project(tmp_path, capsys):
    original = "PostCheckout:\n  ALL:\n    enabled: true\n"
    (tmp_path / ".overcommit.yml").write_text(original)

    sd._configure_post_checkout_hook(tmp_path)

    assert (tmp_path / ".overcommit.yml").read_text() == original
    assert "Overcommit" in capsys.readouterr().err


def test_configure_hook_preserves_conflicting_managers(tmp_path, capsys):
    (tmp_path / "lefthook.yml").write_text("")
    (tmp_path / ".pre-commit-config.yaml").write_text("repos: []\n")

    sd._configure_post_checkout_hook(tmp_path)

    assert (tmp_path / "lefthook.yml").read_text() == ""
    assert (tmp_path / ".pre-commit-config.yaml").read_text() == "repos: []\n"
    err = capsys.readouterr().err
    assert "several hook managers are configured" in err
    assert "lefthook, pre-commit" in err


def test_rn_hook_pre_commit_autofix_warns_until_the_hook_is_installed(tmp_path, monkeypatch):
    _record_manager_installs(monkeypatch)
    (tmp_path / ".pre-commit-config.yaml").write_text("repos:\n  - repo: local\n    hooks:\n")

    sd._ensure_post_checkout_hook(tmp_path)

    assert sd.post_checkout_readiness(tmp_path).ready is True
    assert sd._rn_hook_detect(tmp_path)[0] == "warning"


def test_rn_hook_prek_autofix_warns_until_the_hook_is_installed(tmp_path, monkeypatch):
    _record_manager_installs(monkeypatch)
    (tmp_path / "prek.toml").write_text("")

    sd._ensure_post_checkout_hook(tmp_path)

    assert sd.post_checkout_readiness(tmp_path).ready is True
    assert sd._rn_hook_detect(tmp_path)[0] == "warning"


def test_rn_hook_simple_git_hooks_autofix_warns_until_the_hook_is_installed(tmp_path, monkeypatch):
    _record_manager_installs(monkeypatch)
    (tmp_path / ".simple-git-hooks.json").write_text("{}")

    sd._ensure_post_checkout_hook(tmp_path)

    assert sd.post_checkout_readiness(tmp_path).ready is True
    assert sd._rn_hook_detect(tmp_path)[0] == "warning"


def test_rn_hook_is_ok_once_the_manager_hook_is_installed(tmp_path, monkeypatch):
    _git_init(tmp_path)
    _record_manager_installs(monkeypatch)
    (tmp_path / ".pre-commit-config.yaml").write_text("repos:\n  - repo: local\n    hooks:\n")

    sd._ensure_post_checkout_hook(tmp_path)
    hook = tmp_path / ".git" / "hooks" / "post-checkout"
    hook.parent.mkdir(parents=True, exist_ok=True)
    hook.write_text("#!/bin/sh\n# File generated by pre-commit: https://pre-commit.com\n")

    status, detail = sd._rn_hook_detect(tmp_path)

    assert status == "ok"
    assert detail == "pre-commit forwards post-checkout events"


def test_doctor_reports_a_warning_without_failing(tmp_path, capsys):
    (tmp_path / ".pre-commit-config.yaml").write_text("repos:\n  - repo: local\n    hooks:\n")
    sd.wire_pre_commit(tmp_path)

    assert sd.doctor._run_doctor_targets([(sd.wiring._HOOK_WIRING_CHECK, tmp_path)], fix=False) == 0
    assert "⚠  hook: pre-commit forwards post-checkout events once" in capsys.readouterr().err


def test_rn_hook_overcommit_reports_a_problem(tmp_path):
    (tmp_path / ".overcommit.yml").write_text("PostCheckout:\n")

    status, detail = sd._rn_hook_detect(tmp_path)

    assert status == "problem"
    assert "overcommit" in detail


def test_rn_hook_conflict_reports_a_problem(tmp_path):
    (tmp_path / "lefthook.yml").write_text("")
    (tmp_path / "prek.toml").write_text("")

    status, detail = sd._rn_hook_detect(tmp_path)

    assert status == "problem"
    assert "lefthook, prek" in detail


def test_hook_wiring_check_names_the_pre_commit_config(tmp_path):
    (tmp_path / ".pre-commit-config.yaml").write_text("repos:\n  - repo: local\n    hooks:\n")

    assert sd.wiring._HOOK_WIRING_CHECK.files(tmp_path) == (tmp_path / ".pre-commit-config.yaml",)


def test_hook_wiring_check_names_the_prek_config(tmp_path):
    (tmp_path / "prek.toml").write_text("")

    assert sd.wiring._HOOK_WIRING_CHECK.files(tmp_path) == (tmp_path / "prek.toml",)


def test_hook_wiring_check_names_the_simple_git_hooks_config(tmp_path):
    (tmp_path / "package.json").write_text('{"simple-git-hooks": {"pre-commit": "npm test"}}')

    assert sd.wiring._HOOK_WIRING_CHECK.files(tmp_path) == (tmp_path / "package.json",)


def test_hook_wiring_check_names_nothing_for_overcommit(tmp_path):
    (tmp_path / ".overcommit.yml").write_text("PostCheckout:\n")

    assert sd.wiring._HOOK_WIRING_CHECK.files(tmp_path) == ()


def test_pre_commit_manual_instructions_name_the_event_variables(tmp_path):
    (tmp_path / ".pre-commit-config.yaml").write_text("repos: []\n")

    text = sd.post_checkout_manual_instructions(tmp_path)

    assert "PRE_COMMIT_FROM_REF" in text
    assert "PRE_COMMIT_TO_REF" in text
    assert "PRE_COMMIT_CHECKOUT_TYPE" in text
    assert "always_run" in text
    assert "pre-commit install --hook-type post-checkout" in text


def test_prek_manual_instructions_name_the_prek_install_command(tmp_path):
    (tmp_path / "prek.toml").write_text("")

    text = sd.post_checkout_manual_instructions(tmp_path)

    assert "prek install --hook-type post-checkout" in text


def test_simple_git_hooks_manual_instructions_use_shell_positionals(tmp_path):
    (tmp_path / ".simple-git-hooks.js").write_text("module.exports = {}\n")

    text = sd.post_checkout_manual_instructions(tmp_path)

    assert '\\"$1\\" \\"$2\\" \\"$3\\"' in text
    assert "npx simple-git-hooks" in text


def test_overcommit_manual_instructions_name_the_post_checkout_hook(tmp_path):
    (tmp_path / ".overcommit.yml").write_text("PostCheckout:\n")

    text = sd.post_checkout_manual_instructions(tmp_path)

    assert "PostCheckout" in text
    assert ".overcommit.yml is left untouched" in text


def test_activation_installs_pre_commit_hooks_after_configuration(tmp_path, monkeypatch):
    installs = _record_manager_installs(monkeypatch)
    (tmp_path / ".pre-commit-config.yaml").write_text("repos:\n  - repo: local\n    hooks:\n")
    sd._configure_post_checkout_hook(tmp_path)

    assert sd._activate_post_checkout_hook(tmp_path) is True
    assert installs == [(tmp_path, "pre-commit install --hook-type post-checkout")]


def test_activation_installs_prek_hooks_after_configuration(tmp_path, monkeypatch):
    installs = _record_manager_installs(monkeypatch)
    (tmp_path / "prek.toml").write_text("")
    sd._configure_post_checkout_hook(tmp_path)

    assert sd._activate_post_checkout_hook(tmp_path) is True
    assert installs == [(tmp_path, "prek install --hook-type post-checkout")]


def test_activation_reports_manual_steps_for_an_unconfigured_manager(tmp_path, monkeypatch):
    installs = _record_manager_installs(monkeypatch)
    (tmp_path / ".pre-commit-config.yaml").write_text("repos: []\n")

    assert sd._activate_post_checkout_hook(tmp_path) is False
    assert installs == []


def test_activation_uses_the_checkouts_own_simple_git_hooks_binary(tmp_path, monkeypatch):
    installs = _record_manager_installs(monkeypatch)
    (tmp_path / ".simple-git-hooks.json").write_text("{}")
    sd._configure_post_checkout_hook(tmp_path)
    binary = tmp_path / "node_modules" / ".bin" / "simple-git-hooks"
    binary.parent.mkdir(parents=True)
    binary.write_text("#!/bin/sh\n")

    assert sd._activate_post_checkout_hook(tmp_path) is True
    assert installs == [(tmp_path, "npx simple-git-hooks")]


def test_activation_never_fetches_simple_git_hooks(tmp_path, monkeypatch, capsys):
    installs = _record_manager_installs(monkeypatch)
    (tmp_path / ".simple-git-hooks.json").write_text("{}")
    sd._configure_post_checkout_hook(tmp_path)

    assert sd._activate_post_checkout_hook(tmp_path) is False
    assert installs == []
    assert "simple-git-hooks is not installed in this checkout" in capsys.readouterr().err


def test_activation_reports_husky_hooks_that_are_not_installed(tmp_path, capsys):
    _git_init(tmp_path)
    (tmp_path / ".husky").mkdir()
    sd._configure_post_checkout_hook(tmp_path)

    assert sd._activate_post_checkout_hook(tmp_path) is False
    assert "husky's hooks are not installed in this checkout" in capsys.readouterr().err


def test_activation_accepts_installed_husky_hooks(tmp_path):
    _git_init(tmp_path)
    subprocess.run(["git", "config", "core.hooksPath", ".husky/_"], cwd=tmp_path, check=True)
    (tmp_path / ".husky" / "_").mkdir(parents=True)
    (tmp_path / ".husky" / "_" / "post-checkout").write_text("#!/bin/sh\n")
    sd._configure_post_checkout_hook(tmp_path)

    assert sd._activate_post_checkout_hook(tmp_path) is True


def test_readiness_separates_configuration_from_local_activation(tmp_path):
    (tmp_path / ".pre-commit-config.yaml").write_text("repos:\n  - repo: local\n    hooks:\n")
    sd._configure_post_checkout_hook(tmp_path)

    readiness = sd.post_checkout_readiness(tmp_path)

    assert readiness.ready is True
    assert readiness.active is False
    assert "once its hooks are installed" in readiness.detail


def test_readiness_reports_an_installed_manager_hook_as_active(tmp_path):
    _git_init(tmp_path)
    (tmp_path / ".pre-commit-config.yaml").write_text("repos:\n  - repo: local\n    hooks:\n")
    sd._configure_post_checkout_hook(tmp_path)
    hook = _native_hook(tmp_path)
    hook.parent.mkdir(parents=True, exist_ok=True)
    hook.write_text("#!/bin/sh\n# File generated by pre-commit: https://pre-commit.com\n")

    readiness = sd.post_checkout_readiness(tmp_path)

    assert readiness.active is True
    assert readiness.detail == "pre-commit forwards post-checkout events"


def test_cmd_init_writes_pre_commit_config_without_installing_hooks(tmp_path, monkeypatch):
    installs = _record_manager_installs(monkeypatch)
    _git_init(tmp_path)
    (tmp_path / ".pre-commit-config.yaml").write_text("repos:\n  - repo: local\n    hooks:\n")

    sd.cmd_init(tmp_path)

    assert "- id: splashdown" in (tmp_path / ".pre-commit-config.yaml").read_text()
    assert installs == []
    assert not _native_hook(tmp_path).exists()


def test_wire_husky_is_idempotent(tmp_path, capsys):
    sd._wire_post_checkout_husky(tmp_path)
    capsys.readouterr()

    assert sd._wire_post_checkout_husky(tmp_path) is True
    assert capsys.readouterr().err == ""


def _tracked_notes(err: str) -> list[str]:
    return [
        line.split("note: ")[1].split(" is tracked by git")[0]
        for line in err.splitlines()
        if " is tracked by git" in line
    ]


def test_ensure_gitignore_reports_only_the_tracked_destination_itself(tmp_path, capsys):
    _git_init(tmp_path)
    for name in ("env[dev].env", "envd.env"):
        (tmp_path / name).write_text("PORT=1\n")
    subprocess.run(
        ["git", "--literal-pathspecs", "add", "--", "env[dev].env", "envd.env"],
        cwd=tmp_path,
        check=True,
    )
    sd._ensure_gitignore(tmp_path, ["env[dev].env"])
    assert _tracked_notes(capsys.readouterr().err) == ["env[dev].env"]


def test_ensure_gitignore_reports_a_tracked_destination_named_like_pathspec_magic(tmp_path, capsys):
    _git_init(tmp_path)
    (tmp_path / ":weird.env").write_text("PORT=1\n")
    subprocess.run(
        ["git", "--literal-pathspecs", "add", "--", ":weird.env"], cwd=tmp_path, check=True
    )
    sd._ensure_gitignore(tmp_path, [":weird.env"])
    assert _tracked_notes(capsys.readouterr().err) == [":weird.env"]


def test_ensure_gitignore_reports_overriding_a_user_negation(tmp_path, capsys):
    _git_init(tmp_path)
    (tmp_path / ".gitignore").write_text("*.env\n!important.env\n")
    sd._ensure_gitignore(tmp_path, ["important.env"])
    err = capsys.readouterr().err
    assert "important.env is now ignored by the managed block" in err
    assert "overrides `!important.env` in .gitignore" in err
    assert _git_ignores(tmp_path, "important.env")


def test_ensure_gitignore_reuses_a_rule_from_the_repository_exclude_file(tmp_path):
    _git_init(tmp_path)
    (tmp_path / ".git" / "info").mkdir(exist_ok=True)
    (tmp_path / ".git" / "info" / "exclude").write_text("splashdown.env\n")
    sd._ensure_gitignore(tmp_path, ["splashdown.env"])
    assert (tmp_path / ".gitignore").read_text() == _block("/splashdown.local.toml")


def test_ensure_gitignore_reuses_a_rule_from_a_configured_excludes_file(tmp_path):
    _git_init(tmp_path)
    excludes = tmp_path / "personal-excludes"
    excludes.write_text("splashdown.env\n")
    subprocess.run(["git", "config", "core.excludesFile", str(excludes)], cwd=tmp_path, check=True)
    sd._ensure_gitignore(tmp_path, ["splashdown.env"])
    assert (tmp_path / ".gitignore").read_text() == _block("/splashdown.local.toml")


def test_ensure_gitignore_keeps_crlf_line_endings(tmp_path):
    _git_init(tmp_path)
    (tmp_path / ".gitignore").write_bytes(b"# build output\r\ndist/\r\n")
    sd._ensure_gitignore(tmp_path, ["splashdown.env"])
    raw = (tmp_path / ".gitignore").read_bytes()
    assert b"\n" not in raw.replace(b"\r\n", b"")
    assert raw.startswith(b"# build output\r\ndist/\r\n")
    assert raw.endswith(b"/splashdown.env\r\n" + sd.hooks.GITIGNORE_END.encode() + b"\r\n")


def test_revert_gitignore_drops_only_the_separator_blank_line(tmp_path):
    (tmp_path / ".gitignore").write_text("dist/\n\n\n" + _block("/splashdown.env"))
    sd._revert_gitignore(tmp_path)
    assert (tmp_path / ".gitignore").read_text() == "dist/\n\n"


def test_revert_gitignore_removes_a_block_between_user_rules(tmp_path):
    (tmp_path / ".gitignore").write_text(
        "dist/\n\n" + _block("/splashdown.local.toml", "/splashdown.env") + "\n*.log\n"
    )
    sd._revert_gitignore(tmp_path)
    assert (tmp_path / ".gitignore").read_text() == "dist/\n\n*.log\n"


def test_revert_gitignore_leaves_duplicate_markers_alone(tmp_path, capsys):
    original = _block("/splashdown.local.toml") + _block("/splashdown.env")
    (tmp_path / ".gitignore").write_text(original)
    sd._revert_gitignore(tmp_path)
    assert (tmp_path / ".gitignore").read_text() == original
    assert "left .gitignore alone" in capsys.readouterr().err


def test_revert_gitignore_leaves_an_unclosed_marker_alone(tmp_path, capsys):
    original = sd.hooks.GITIGNORE_BEGIN + "\n/splashdown.env\n"
    (tmp_path / ".gitignore").write_text(original)
    sd._revert_gitignore(tmp_path)
    assert (tmp_path / ".gitignore").read_text() == original
    assert "left .gitignore alone" in capsys.readouterr().err


def test_revert_gitignore_leaves_a_reversed_marker_pair_alone(tmp_path, capsys):
    original = f"{sd.hooks.GITIGNORE_END}\n/splashdown.env\n{sd.hooks.GITIGNORE_BEGIN}\n"
    (tmp_path / ".gitignore").write_text(original)
    sd._revert_gitignore(tmp_path)
    assert (tmp_path / ".gitignore").read_text() == original
    assert "left .gitignore alone" in capsys.readouterr().err


def test_ensure_gitignore_ignores_a_developers_personal_git_ignore_file(tmp_path, monkeypatch):
    xdg = tmp_path / "personal-xdg"
    (xdg / "git").mkdir(parents=True)
    (xdg / "git" / "ignore").write_text("*.env\n")
    monkeypatch.setenv("XDG_CONFIG_HOME", str(xdg))
    _git_init(tmp_path)
    sd._ensure_gitignore(tmp_path, ["splashdown.env"])
    assert (tmp_path / ".gitignore").read_text() == _block(
        "/splashdown.local.toml", "/splashdown.env"
    )


def test_rn_pkg_autofix_keeps_the_formatting_it_did_not_write(tmp_path):
    original = (
        "{\n"
        '\t"name": "app",\n'
        '\t"scripts": {\n'
        '\t\t"start": "react-native start --port 8081",\n'
        '\t\t"lint": "eslint ."\n'
        "\t},\n"
        '\t"dependencies": { "react-native": "0.83" }\n'
        "}\n"
    )
    (tmp_path / "package.json").write_text(original)

    sd._rn_pkg_autofix(tmp_path)

    text = (tmp_path / "package.json").read_text()
    assert '\t\t"start": "react-native start",\n' in text
    assert '\t\t"lint": "eslint ."\n' in text
    assert '\t"dependencies": { "react-native": "0.83" }\n' in text
    assert text.count("\t") == original.count("\t")


def test_rn_pkg_autofix_strips_every_script_in_one_pass(tmp_path):
    (tmp_path / "package.json").write_text(
        '{"scripts": {"start": "react-native start --port 8081",'
        ' "ios": "react-native run-ios --port 8081"}}\n'
    )

    sd._rn_pkg_autofix(tmp_path)

    scripts = json.loads((tmp_path / "package.json").read_text())["scripts"]
    assert scripts == {"start": "react-native start", "ios": "react-native run-ios"}


@pytest.mark.parametrize("character", ["\x0b", "\x0c", "\x1c", "\x1d", "\x1e", "\x85"])
def test_lefthook_wiring_keeps_a_line_break_lookalike_inside_a_value(tmp_path, character):
    original = (
        "pre-commit:\n"
        "  commands:\n"
        "    lint:\n"
        f'      run: echo "a{character}b"\n'
        "post-checkout:\n"
        "  commands:\n"
        "    other:\n"
        "      run: echo hi\n"
    )
    (tmp_path / "lefthook.yml").write_text(original, encoding="utf-8")

    assert sd.hooks._wire_post_checkout_lefthook(tmp_path) is True

    text = (tmp_path / "lefthook.yml").read_text(encoding="utf-8")
    assert f'      run: echo "a{character}b"\n' in text
    assert "    splashdown:\n" in text


def test_lefthook_wiring_keeps_crlf_line_endings(tmp_path):
    original = b"post-checkout:\r\n  commands:\r\n    other:\r\n      run: echo hi\r\n"
    (tmp_path / "lefthook.yml").write_bytes(original)

    assert sd.hooks._wire_post_checkout_lefthook(tmp_path) is True

    raw = (tmp_path / "lefthook.yml").read_bytes()
    assert raw.count(b"\r\n") == raw.count(b"\n")
    assert b"    splashdown:\r\n" in raw
