"""TOML *writing* — the one place that serializes/edits splashdown's TOML files.

Uses `tomlkit` (not stdlib `tomllib`) because every edit here must preserve the
user's comments and unknown keys on round-trip. (One known gap: `refresh_recipe`
replaces the `[apps.*]` tables wholesale, so a standalone comment sitting in the
gap between the last `[apps.*]` and the first `[resources.*]` is dropped; comments
inside tables, inline comments, and the file header all survive.) Reads stay on
`tomllib` in recipe.py. This module is the ONLY importer of tomlkit, and it is lazy-imported
by its callers (commands.py / targets.py / hooks.py), so the git-hook hot path — which only
reads TOML — never loads tomlkit. Do not import this module at the top level of
anything on the read path, and do not re-export it from `__init__.py`.

All functions are pure `str -> str` (or `str | None`) transforms; callers own the
file I/O and any printing.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, cast

import tomlkit
from tomlkit import array, comment, document, key, nl, table
from tomlkit.items import Table

from .constants import ENV_FILE_NAME

if TYPE_CHECKING:
    from collections.abc import Mapping
    from pathlib import Path

    from .inventory import AppInventory, ProjectInventory

_HEADER = (
    "splashdown.toml — auto-generated by `splash init`. Edit freely;",
    "comments are kept when splashdown re-scans; all fields are strictly validated.",
)


def _app_table(app: AppInventory, resource_names: list[str], cwd: Path) -> Table:
    t = table()
    t["path"] = "." if app.path == cwd else str(app.path.relative_to(cwd))
    t["profile"] = app.profile
    arr = array()
    arr.extend(resource_names)
    t["resources"] = arr
    return t


def _resource_table(spec: dict[str, Any]) -> Table:
    rt = table()
    for k, v in spec.items():
        rt[k] = v
    return rt


def _set_apps(
    doc: Any, inv: ProjectInventory, app_resource_names: dict[str, list[str]], cwd: Path
) -> None:
    if not inv.apps:
        if "apps" in doc:
            del doc["apps"]
        return
    apps = table()
    for app in inv.apps:
        apps[app.name] = _app_table(app, app_resource_names.get(app.name, []), cwd)
    doc["apps"] = apps


def render_scanned_recipe(
    inv: ProjectInventory,
    merged_resources: dict[str, dict[str, Any]],
    app_resource_names: dict[str, list[str]],
    cwd: Path,
    merged_targets: dict[str, dict[str, dict[str, str]]] | None = None,
    project_metadata: Mapping[str, Mapping[str, str]] | None = None,
) -> str:
    """Render a fresh recipe (header comment, [project], [apps.*], [resources.*],
    [targets.*])."""
    doc = document()
    for line in _HEADER:
        doc.add(comment(line))
    doc.add(nl())
    proj = table()
    proj["workspace"] = inv.workspace
    proj["loader"] = inv.loader
    for name, fields in (project_metadata or {}).items():
        nested = table()
        for field, value in fields.items():
            nested[field] = value
        proj[name] = nested
    doc["project"] = proj
    _set_apps(doc, inv, app_resource_names, cwd)
    if merged_resources:
        res = table()
        for name, spec in merged_resources.items():
            res[name] = _resource_table(spec)
        doc["resources"] = res
    for dtype, variants in (merged_targets or {}).items():
        for variant, fields in variants.items():
            _add_target(doc, dtype, variant, fields)
    return tomlkit.dumps(doc)


def _add_target(doc: Any, dtype: str, variant: str, fields: Mapping[str, str | None]) -> None:
    """Add a [targets.<dtype>.<variant>] table; `None`-valued fields are skipped."""
    if "targets" not in doc:
        doc["targets"] = table()
    targets = cast(Table, doc["targets"])
    if dtype not in targets:
        targets[dtype] = table()
    bucket = cast(Table, targets[dtype])
    leaf = table()
    for k, v in fields.items():
        if v is not None:
            leaf[k] = v
    bucket[variant] = leaf


def refresh_recipe(
    existing_text: str,
    inv: ProjectInventory,
    profile_resources: dict[str, dict[str, Any]],
    app_resource_names: dict[str, list[str]],
    cwd: Path,
) -> str:
    """Re-scan rewrite: replace [project]/[apps.*] but keep existing [resources.*]
    (and all comments/unknown keys) intact. `profile_resources` are the freshly
    emitted specs; only those NOT already present are appended. [project] is
    mutated in place so a leading header comment survives."""
    doc = tomlkit.parse(existing_text)
    if "project" in doc:
        proj = cast(Table, doc["project"])
    else:
        proj = table()
        doc["project"] = proj
    proj["workspace"] = inv.workspace
    # An explicit `loader = "none"` is an opt-out, not a stale scan result — a
    # rescan on a machine that happens to have mise installed must not undo it.
    if proj.get("loader") != "none":
        proj["loader"] = inv.loader
    _set_apps(doc, inv, app_resource_names, cwd)
    if profile_resources:
        if "resources" in doc:
            res = cast(Table, doc["resources"])
        else:
            res = table()
            doc["resources"] = res
        for name, spec in profile_resources.items():
            if name not in res:
                res[name] = _resource_table(spec)
    return tomlkit.dumps(doc)


def ensure_mise_file_directive_text(existing_text: str | None) -> str | None:
    """Return mise config text with `_.file = "<env file>"` ensured under [env].
    `None` input scaffolds a new file; `None` output means it was already present
    (caller should not rewrite)."""
    if existing_text is None:
        doc = document()
        env = table()
        env[key(["_", "file"])] = ENV_FILE_NAME
        doc["env"] = env
        return tomlkit.dumps(doc)
    doc = tomlkit.parse(existing_text)
    env_tbl = cast(Table, doc["env"]) if "env" in doc else None
    underscore: Any = env_tbl["_"] if env_tbl is not None and "_" in env_tbl else None
    if isinstance(underscore, dict) and underscore.get("file") == ENV_FILE_NAME:
        return None
    if env_tbl is None:
        env_tbl = table()
        doc["env"] = env_tbl
    if isinstance(underscore, dict):
        # `_` already exists as a table (dotted `_.x` keys or the `[env._]` subtable
        # form, e.g. a user's `_.path`). Set `file` in place — re-adding it as a new
        # dotted key would raise KeyAlreadyPresent or double-declare `[env._]`.
        underscore["file"] = ENV_FILE_NAME
    else:
        env_tbl[key(["_", "file"])] = ENV_FILE_NAME
    return tomlkit.dumps(doc)


def remove_mise_file_directive_text(existing_text: str | None) -> str | None:
    """Inverse of ensure_mise_file_directive_text: drop `_.file = "<env file>"`
    from [env]. Empties the `_` and `[env]` tables that nothing else occupies.
    Returns the new text to write; an empty string when removal leaves the
    document empty (caller should delete the file); or `None` when there is
    nothing of ours to remove (caller should not rewrite)."""
    if existing_text is None:
        return None
    doc = tomlkit.parse(existing_text)
    env_tbl = cast(Table, doc["env"]) if "env" in doc else None
    if env_tbl is None:
        return None
    underscore: Any = env_tbl.get("_")
    if not (isinstance(underscore, dict) and underscore.get("file") == ENV_FILE_NAME):
        return None
    del underscore["file"]
    if not underscore:
        del env_tbl["_"]
    if not env_tbl:
        del doc["env"]
    return tomlkit.dumps(doc)


def target_add_text(
    existing_text: str, dtype: str, variant: str, fields: Mapping[str, str | None]
) -> str:
    """Add a [targets.<dtype>.<variant>] table with the given string fields."""
    doc = tomlkit.parse(existing_text)
    _add_target(doc, dtype, variant, fields)
    return tomlkit.dumps(doc)


def target_remove_text(existing_text: str, dtype: str, variant: str) -> str | None:
    """Delete [targets.<dtype>.<variant>], pruning empty parents. `None` if absent."""
    doc = tomlkit.parse(existing_text)
    targets = doc.get("targets")
    if targets is None or dtype not in targets:
        return None
    bucket = cast(Table, targets[dtype])
    if variant not in bucket:
        return None
    del bucket[variant]
    if not bucket:
        del cast(Table, targets)[dtype]
    if not cast(Table, targets):
        del doc["targets"]
    return tomlkit.dumps(doc)
