"""TOML rendering and comment-preserving edits."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, cast

import tomlkit
from tomlkit import array, comment, document, key, nl, table
from tomlkit.items import Table

from .constants import normalized_env_reference

if TYPE_CHECKING:
    from collections.abc import Mapping
    from pathlib import Path

    from .inventory import AppInventory, ProjectInventory

_HEADER = (
    "splashdown.toml — auto-generated by `splash init`. Edit freely;",
    "all fields are strictly validated.",
)


def _app_table(app: AppInventory, resource_names: list[str], cwd: Path) -> Table:
    t = table()
    t["path"] = "." if app.path == cwd else str(app.path.relative_to(cwd))
    t["profile"] = app.profile
    arr = array()
    arr.extend(resource_names)
    t["resources"] = arr
    return t


def _resource_table(spec: dict[str, Any]) -> Table:
    rt = table()
    for k, v in spec.items():
        rt[k] = v
    return rt


def _set_apps(
    doc: Any, inv: ProjectInventory, app_resource_names: dict[str, list[str]], cwd: Path
) -> None:
    if not inv.apps:
        return
    apps = table()
    for app in inv.apps:
        apps[app.name] = _app_table(app, app_resource_names.get(app.name, []), cwd)
    doc["apps"] = apps


def render_scanned_recipe(
    inv: ProjectInventory,
    merged_resources: dict[str, dict[str, Any]],
    app_resource_names: dict[str, list[str]],
    cwd: Path,
    merged_targets: dict[str, dict[str, dict[str, str]]] | None = None,
    project_metadata: Mapping[str, str | Mapping[str, str]] | None = None,
) -> str:
    """Render a fresh recipe (header comment, [project], [apps.*], [resources.*],
    [targets.*])."""
    doc = document()
    for line in _HEADER:
        doc.add(comment(line))
    doc.add(nl())
    proj = table()
    proj["workspace"] = inv.workspace
    proj["loader"] = inv.loader
    for name, fields in (project_metadata or {}).items():
        if isinstance(fields, str):
            proj[name] = fields
            continue
        nested = table()
        for field, value in fields.items():
            nested[field] = value
        proj[name] = nested
    doc["project"] = proj
    _set_apps(doc, inv, app_resource_names, cwd)
    if merged_resources:
        res = table()
        for name, spec in merged_resources.items():
            res[name] = _resource_table(spec)
        doc["resources"] = res
    for dtype, variants in (merged_targets or {}).items():
        for variant, fields in variants.items():
            _add_target(doc, dtype, variant, fields)
    return tomlkit.dumps(doc)


def _add_target(doc: Any, dtype: str, variant: str, fields: Mapping[str, str | None]) -> None:
    """Add a [targets.<dtype>.<variant>] table; `None`-valued fields are skipped."""
    if "targets" not in doc:
        doc["targets"] = table()
    targets = cast(Table, doc["targets"])
    if dtype not in targets:
        targets[dtype] = table()
    bucket = cast(Table, targets[dtype])
    leaf = table()
    for k, v in fields.items():
        if v is not None:
            leaf[k] = v
    bucket[variant] = leaf


MISE_MANAGED_MARKER = "splashdown-managed"


def _mise_env_file_entries(value: Any) -> list[str] | None:
    """The `_.file` slot as a list of plain strings, or `None` when it holds a
    shape splashdown cannot edit without discarding it."""
    if isinstance(value, str):
        return [str(value)]
    if isinstance(value, list) and all(isinstance(entry, str) for entry in value):
        return [str(entry) for entry in value]
    return None


def _mise_env_file_slot(doc: Any) -> tuple[Any, Any, Any]:
    """`([env] table, `_` table, `file` value)`, each `None` when absent."""
    env_tbl = doc.get("env")
    if env_tbl is not None and not isinstance(env_tbl, dict):
        raise ValueError("`env` is not a table")
    underscore = env_tbl.get("_") if env_tbl is not None else None
    if underscore is not None and not isinstance(underscore, dict):
        raise ValueError("`env._` is not a table")
    current = underscore.get("file") if isinstance(underscore, dict) else None
    if current is not None and _mise_env_file_entries(current) is None:
        raise ValueError("`env._.file` is neither a string nor a list of strings")
    return env_tbl, underscore, current


def _comment_text(value: Any) -> str:
    trivia = getattr(value, "trivia", None)
    return str(getattr(trivia, "comment", "") or "").lstrip("#").strip()


def _mark(value: Any) -> Any:
    text = _comment_text(value)
    if MISE_MANAGED_MARKER not in text.split():
        value.comment(f"{text} {MISE_MANAGED_MARKER}".strip())
    return value


def _marked(value: Any) -> Any:
    return _mark(tomlkit.item(value))


def _widened(current: Any, entries: list[str]) -> Any:
    value = tomlkit.item(entries)
    if text := _comment_text(current):
        value.comment(text)
    return _mark(value)


def _clear_marker(value: Any) -> None:
    remaining = " ".join(
        word for word in _comment_text(value).split() if word != MISE_MANAGED_MARKER
    )
    if remaining:
        value.comment(remaining)
    else:
        value.trivia.comment = ""
        value.trivia.comment_ws = ""


def _is_marked(value: Any) -> bool:
    return MISE_MANAGED_MARKER in _comment_text(value).split()


def ensure_mise_file_directive_text(existing_text: str | None, env_file: str) -> str | None:
    """Return mise config text whose `[env]` `_.file` slot loads the env file.
    `None` input scaffolds a new file; `None` output means an existing directive
    already names the file, so the caller must not rewrite it. Raises ValueError
    for a slot splashdown cannot extend."""
    if existing_text is None:
        doc = document()
        env = table()
        env[key(["_", "file"])] = _marked(env_file)
        doc["env"] = env
        return tomlkit.dumps(doc)
    doc = tomlkit.parse(existing_text)
    env_tbl, underscore, current = _mise_env_file_slot(doc)
    entries = _mise_env_file_entries(current) if current is not None else None
    if entries is not None and any(
        normalized_env_reference(entry) == env_file for entry in entries
    ):
        return None
    if env_tbl is None:
        env_tbl = table()
        doc["env"] = env_tbl
    if current is None:
        value = _marked(env_file)
    elif isinstance(current, str):
        value = _widened(current, [str(current), env_file])
    else:
        current.append(env_file)
        value = _mark(current)
    if isinstance(underscore, dict):
        # `_` already exists as a table (dotted `_.x` keys or the `[env._]` subtable
        # form, e.g. a user's `_.path`). Set `file` in place — re-adding it as a new
        # dotted key would raise KeyAlreadyPresent or double-declare `[env._]`.
        underscore["file"] = value
    else:
        env_tbl[key(["_", "file"])] = value
    return tomlkit.dumps(doc)


def mise_file_directive_is_managed(existing_text: str | None) -> bool:
    """Whether the `_.file` slot carries splashdown's marker comment, which is
    what makes the directive splashdown's to remove."""
    if existing_text is None:
        return False
    try:
        doc = tomlkit.parse(existing_text)
        _, _, current = _mise_env_file_slot(doc)
    except ValueError:
        return False
    return current is not None and _is_marked(current)


def remove_mise_file_directive_text(existing_text: str | None, env_file: str) -> str | None:
    """Inverse of ensure_mise_file_directive_text: drop the env file from a
    marked `_.file` slot. The marker says splashdown put an entry in the slot,
    not that it owns the slot, so removal is entry-scoped: other entries stay,
    their trivia keeps whatever the user wrote, and the `_` and `[env]` tables
    are pruned only when nothing else occupies them. A slot splashdown widened
    from a string stays a list, because a one-entry remainder cannot be told
    apart from a list the user wrote. Returns the new text to write; an empty
    string when removal leaves the document empty (caller should delete the
    file); or `None` when there is nothing of ours to remove."""
    if existing_text is None:
        return None
    doc = tomlkit.parse(existing_text)
    env_tbl, underscore, current = _mise_env_file_slot(doc)
    if current is None or not _is_marked(current):
        return None
    entries = _mise_env_file_entries(current) or []
    ours = [entry for entry in entries if normalized_env_reference(entry) == env_file]
    if not ours:
        return None
    if len(ours) < len(entries):
        for entry in ours:
            cast(Any, current).remove(entry)
        _clear_marker(current)
    else:
        del cast(Any, underscore)["file"]
        if not underscore:
            del cast(Table, env_tbl)["_"]
        if not env_tbl:
            del doc["env"]
    return _without_added_trailing_blank(tomlkit.dumps(doc), existing_text)


def _without_added_trailing_blank(text: str, original: str) -> str:
    """A removed table takes back the blank line tomlkit inserted ahead of it, so
    teardown leaves the file as it found it instead of one blank line longer."""
    if not text.strip():
        return ""
    if original.endswith("\n\n") or not text.endswith("\n\n"):
        return text
    return text.rstrip("\n") + "\n"


def target_add_text(
    existing_text: str, dtype: str, variant: str, fields: Mapping[str, str | None]
) -> str:
    """Add a [targets.<dtype>.<variant>] table with the given string fields."""
    doc = tomlkit.parse(existing_text)
    _add_target(doc, dtype, variant, fields)
    return tomlkit.dumps(doc)


def target_remove_text(existing_text: str, dtype: str, variant: str) -> str | None:
    """Delete [targets.<dtype>.<variant>], pruning empty parents. `None` if absent."""
    doc = tomlkit.parse(existing_text)
    targets = doc.get("targets")
    if targets is None or dtype not in targets:
        return None
    bucket = cast(Table, targets[dtype])
    if variant not in bucket:
        return None
    del bucket[variant]
    if not bucket:
        del cast(Table, targets)[dtype]
    if not cast(Table, targets):
        del doc["targets"]
    return tomlkit.dumps(doc)
